<?php

/**
 * @file
 * dosomething_modal.module
 *
 *  Based on the ctools-ajax-example module, provides wrappers and helpers for ctools modals.
 *
 **/
include_once 'dosomething_modal.examples.inc';

/**
 * Implements hook_menu().
 */
function dosomething_modal_menu() {
  $items['ds-modal/example'] = array(
    'title' => 'DoSomething Modal Examples',
    'page callback' => 'dosomething_modal_example_page',
    'access arguments' => array('administer modules'),
    'type' => MENU_CALLBACK,
    'file' => 'dosomething_modal.examples.inc',
  );
  $items['ds-modal/%ctools_js/form/%'] = array(
    'title' => 'DoSomething',
    'page callback' => 'dosomething_modal_form_builder',
    'page arguments' => array(1, 3),
    'access callback' => 'dosomething_modal_form_builder_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Access callback: Whether or not a given form can be displayed ctools modal.
 *
 * @param string $form_id
 *   The form_id to render.
 *
 * @return boolean
 *
 * @see dosomething_modal_menu()
 */
function dosomething_modal_form_builder_access($form_id) {
  // Only authenticated users should be submitting modal forms.  
  if (!user_is_logged_in()) {
    return FALSE;
  }
  // Sanitize string from URL:
  $form_id = check_plain($form_id);
  // We check for allowed form_ids to prevent a user from passing through any form_id into the URL.
  $allowed_forms = array(
    'dosomething_modal_example_form',
    'dosomething_campaign_momm_signup_data_form',
    'dosomething_campaign_tfj_signup_data_form',
  );
  // If it's not allowed, no soup for you.
  return in_array($form_id, $allowed_forms);
}

/**
 * Page callback: Displays a given form in ctools modal.
 *
 * $form_id must be defined in dosomething_modal_form_builder_access for security.
 *
 * @param string $ajax
 *   Whether or not the user has javascript enabled.
 * @param string $form_id
 *   The form_id to pass through.
 *
 * @return mixed
 *   Prints form using ajax_render if javascript.  Returns the form on the page if no js.
 *
 * @see dosomething_modal_menu()
 */
function dosomething_modal_form_builder($ajax, $form_id) {
  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');
 
    $form_state = array(
      'ajax' => TRUE,
    //  'title' => t('To Be Dynamic'),
    );
 
    // Use ctools to generate ajax instructions for the browser to create
    // the form in a modal popup.
    $output = ctools_modal_form_wrapper($form_id, $form_state);
 
    // If the form has been submitted, there may be additional instructions
    // such as dismissing the modal popup.
    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }
 
    // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return drupal_get_form($form_id);
  }
}

/**
 * Render text as a link which opens given $form_id in a ctools modal.
 *
 * @param string $text
 *   The text that will be displayed as the link
 * @param string $form_id
 *   The form_id to render in the modal.
 * @param array $options
 *   A settings array used to style the modal, indexed by the class to use.
 * @param string $class
 *   The class to apply to the link, which defines what modal to use.
 *
 * @return string
 *   Returns markup.
 *
 * @see ctools_modal_text_button()
 */
function dosomething_modal_form_link($text, $form_id, $options = array()) {
  // Include necessary CTools stuff:
  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();
  // Check if options have been passed:
  if (!empty($options)) {
    // Use the options array key as the modal class:
    foreach ($options as $key => $values) {
      $class = $key;
      $options = $values;
      break;
    }
  }
  else {
    $class = 'ds-modal';
  }
  // Include the default and/or given modal options:
  $js_settings = dosomething_modal_get_js_settings($class, $options);
  drupal_add_js($js_settings, 'setting');
  // Link to JS for modalTheme DosomethingModalBase:
  ctools_add_js('dosomething-modal', 'dosomething_modal');
  ctools_add_css('dosomething-modal', 'dosomething_modal');
  // Ctools requires the ctools-modal- prefix in order for the magic to happen:
  $class = 'ctools-modal-' . $class;
  // Output a link to the DS Modal Form builder menu callback:
  return ctools_modal_text_button(t($text), 'ds-modal/nojs/form/' . $form_id, t($text), $class);
}

/**
 * Return a settings array to for adding modal JS for a given $class_name.
 *
 * @param string $clsas_name
 *   The class name that will be applied to a ctools modal text button.
 * @param array $overrides
 *   A settings array used to override the default settings.
 *
 * @return array
 *   Returns a settings array.
 *
 * @see dosomething_modal_form_link()
 */
function dosomething_modal_get_js_settings($class_name, $overrides = array()) {
  // Override defaults with any given options:
  $settings = array_merge(dosomething_modal_get_default_js_settings(), $overrides);
  // Ctools expects the array key to be the class
  return array($class_name => $settings);
}

/**
 * Returns an array with default values to use for the modal JS settings.
 *
 * A tutorial of the various settings can be found at 
 * http://www.planetdrum.org/drupal/sites/all/modules/ctools/help/modal.html.
 */
function dosomething_modal_get_default_js_settings() {
  return array(
    // Defines the size of the modal window.
    'modalSize' => array(
      // Can set to "fixed" or "scale".
      'type' => 'scale',
      // Pixel values for "fixed", should be a percentage if "scale".
      'width' => 0.7,
      'height' => 0.8,
    ),
    // Defines the overlay.
    'modalOptions' => array(
      'opacity' => .5,
      'background-color' => '#000',
    ),
    'animation' => 'fadeIn',
    // modalTheme value corresponds to the prototype.name in the JS file.
    // @see js/dosomething-modal.js
    'modalTheme' => 'DosomethingModalBase',
    'closeText' => 'X',
    // Throbber image for when modal is loading.
    'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'ctools_ajax_sample'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
  );
}