<?php
/**
 * @file
 * Code for the DoSomething Mobile Referral Form feature.
 */

include_once 'dosomething_mobile_referral_form.features.inc';

define('MCOMMONS_ALPHAS_CAMPAIGN', 121441);
define('MCOMMONS_BETAS_CAMPAIGN', 121491);

function dosomething_mobile_referral_form_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['dosomething_mobile_referral_form'])) {
    $group = $implementations['dosomething_mobile_referral_form'];
    unset($implementations['dosomething_mobile_referral_form']);
    $implementations['dosomething_mobile_referral_form'] = $group;
  }
}

function dosomething_mobile_referral_form_form_alter(&$form, &$form_state, $form_id) {
  $node = menu_get_object();

  if (strpos($form_id, 'webform_client_form_') === 0 && isset($form_state['webform_entity']) && $form_state['webform_entity']['bundle'] == 'mobile_referral_form') {
    $top = $node->field_top_of_form_html[LANGUAGE_NONE][0]['value'];
    $bottom = $node->field_bottom_of_form_html[LANGUAGE_NONE][0]['value'];

    $u = &$form['submitted'];

    $u['header'] = array(
      '#type' => 'container',
      '#weight' => -10,
      'header' => array(
        '#markup' => $top,
      ),
    );

    $u['bar'] = array(
      '#type' => 'container',
      '#weight' => 1.5,
      '#attributes' => array(
        'id' => 'form-separator',
      ),
      'bar' => array(
        '#markup' => '',
      ),
    );

    $u['footer'] = array(
      '#type' => 'container',
      '#attributes' => array(
        'id' => 'form_footer',
      ),
      '#weight' => 100,
      'bottom' => array(
        '#markup' => $bottom,
      ),
    );

    if (!isset($form_state['alphas'])) {
      if (isset($node->field_referral_alphas_campaign[LANGUAGE_NONE][0]['value']) && !empty($node->field_referral_alphas_campaign[LANGUAGE_NONE][0]['value'])) {
        $form_state['alphas'] = $node->field_referral_alphas_campaign[LANGUAGE_NONE][0]['value'];
      }
    }
    if (!isset($form_state['betas'])) {
      if (isset($node->field_referral_betas_campaign[LANGUAGE_NONE][0]['value']) && !empty($node->field_referral_betas_campaign[LANGUAGE_NONE][0]['value'])) {
        $form_state['betas'] = $node->field_referral_betas_campaign[LANGUAGE_NONE][0]['value'];
      }
    }

    $form['#submit'][] = 'dosomething_mobile_referral_form_wild_submit';
  }

  if (isset($form_state['build_info']['args'][0]->title) && $form_state['build_info']['args'][0]->title == 'Mobile Referral Form' && $node->nid) {
    drupal_add_css(drupal_get_path('module', 'dosomething_mobile_referral_form') . '/css/mobile_referrals.css', array(
        'group' => CSS_THEME,
        'weight' => 10
    ));
    drupal_add_js(drupal_get_path('module', 'dosomething_mobile_referral_form') . '/js/mobile_referrals.js');

    if (!isset($form_state['goto'])) $form_state['goto'] = $_SERVER['REQUEST_URI'];
    $u = &$form['submitted'];

    $form['actions']['submit']['#value'] = 'SEND';
    $form['actions']['submit']['#attributes'] = array('class' => array('go-button'));
    if (!user_is_logged_in()) {
      $form['actions']['submit']['#ajax'] = array(
        'callback' => 'dosomething_mobile_referral_form_ajax',
      );
    }

    if ($node->type == 'tips_and_tools') {
      $tac = ($u['referall_your_info']['terms_and_conditions']);
      unset($u['referall_your_info']['terms_and_conditions']);
      $form['tac'] = $tac;
    }

    if (!isset($form_state['referenced'])) {
      $u['scholarship_reference']['#webform_component']['value'] = $node->title . ' (' . $node->nid . ')';
      $u['scholarship_reference']['#default_value'] = $node->title . ' (' . $node->nid . ')';
      $form_state['referenced'] = TRUE;
    }

    $form['#validate'][] = 'dosomething_mobile_referral_form_validate';
    if ($node->type == 'social_scholarship') {
      if (!isset($form_state['nid'])) {
        $form_state['nid'] = $node->nid;
      }


      if (!isset($form_state['alphas'])) {
        if (isset($node->field_alphas_campaign[LANGUAGE_NONE][0]['value']) && !empty($node->field_alphas_campaign[LANGUAGE_NONE][0]['value'])) {
          $form_state['alphas'] = $node->field_alphas_campaign[LANGUAGE_NONE][0]['value'];
        }
      }
      if (!isset($form_state['betas'])) {
        if (isset($node->field_betas_campaign[LANGUAGE_NONE][0]['value']) && !empty($node->field_betas_campaign[LANGUAGE_NONE][0]['value'])) {
          $form_state['betas'] = $node->field_betas_campaign[LANGUAGE_NONE][0]['value'];
        }
      }

      if (isset($node->field_official_rules_document[LANGUAGE_NONE][0]['filename']) && !empty($node->field_official_rules_document[LANGUAGE_NONE][0]['filename'])) {
        $form['submitted']['referall_your_info']['terms_and_conditions']['#markup'] = str_replace('these official rules', l(t('these official rules'), 'files/social_scholarships/official_rules/' . $node->field_official_rules_document[LANGUAGE_NONE][0]['filename'], array(
        'attributes' => array('target' => '_blank'))), $form['submitted']['referall_your_info']['terms_and_conditions']['#markup']);
      }

      $form_state['goto'] = 'share-these-images/' . $node->nid;
    }
    $form['#submit'][] = 'dosomething_mobile_referral_form_submit';
  }
}

function redirect_to_shary_stats($form, &$form_state) {
  $nid = $form_state['nid'];
  $form_state['redirect'] = 'share-these-images/' . $nid;
  $_GET['redirect'] = 'share-these-images/' . $nid;
}

function dosomething_mobile_referral_form_ajax($form, &$form_state) {
  $commands = array();
  $errors = form_get_errors();
  if ($errors) {
    $error_list = '';
    foreach ($errors AS $key => $error) {
      $error_list .= '<li>' . $error . '</li>';
    }

    $fake_error_template = '<div class="messages error">
      <h2 class="element-invisible">Error message</h2>
      <ul>' . $error_list . '</ul></div>
    ';
    $commands[] = ajax_command_before('#page-title', $fake_error_template);
  }
  else {
    $commands[] = ajax_command_invoke('#dosomething-login-register-popup-form', 'dsReferSubmit', array($form_state['goto'], $form_state['input']['submitted']['referall_your_info']['referral_first_name'], $form_state['input']['submitted']['referall_your_info']['referral_phone_number']));
  }

  return array(
    '#type' => 'ajax',
    '#commands' => $commands
  );
}

function dosomething_mobile_referral_form_validate($form, &$form_state) {
  $error = 0;
  $s = $form_state['input']['submitted'];
  $you = $s['referall_your_info'];
  $them = $s['referral_friend_info'];

  if (trim($you['referral_first_name']) == '') {
    form_set_error('submitted[referall_your_info][referral_first_name]', "You must provide a valid name.");
    $error++;
  }

  if (!dosomething_general_valid_cell($you['referral_phone_number'])) {
    form_set_error('submitted[referall_your_info][referral_phone_number', "Your phone number must be a valid phone number.");
    $error++;
  }

  if (!dosomething_general_valid_cell($them['referral_friend_cell_1'])) {
    form_set_error('submitted[referral_friend_info][referral_friend_cell_1', "You must provide at least one valid cell phone number.");
    $error++;
  }

  if ($error > 0 && user_is_logged_in()) {
    drupal_goto($_SERVER['HTTP_REFERER']);
  }
}

function dosomething_mobile_referral_form_wild_submit($form, &$form_state) {
  $s = $form_state['input']['submitted'];
  $you = array(
    'name' => $s['field_referral_your_name'][LANGUAGE_NONE][0]['value'],
    'cell' => $s['field_referral_your_cell'][LANGUAGE_NONE][0]['value'],
  );
  $them = array(
    1 => $s['field_cell_friend1'][LANGUAGE_NONE][0]['value'],
    2 => $s['field_cell_friend2'][LANGUAGE_NONE][0]['value'],
    3 => $s['field_cell_friend3'][LANGUAGE_NONE][0]['value'],
    4 => $s['field_cell_friend4'][LANGUAGE_NONE][0]['value'],
    5 => $s['field_cell_friend5'][LANGUAGE_NONE][0]['value'],
    6 => $s['field_cell_friend6'][LANGUAGE_NONE][0]['value'],
  );

  if (user_is_logged_in()) {
    global $user;
    $profile = profile2_load_by_user($user, 'main');
    if (!$profile->field_user_mobile[LANGUAGE_NONE][0]['value'] || $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] !== $you['cell']) {
       $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] = $you['cell'];
       $profile->save();
    }
  }

  $alphas_campaign = MCOMMONS_ALPHAS_CAMPAIGN;
  if ($form_state['alphas']) {
    $alphas_campaign = $form_state['alphas'];
  }

  $betas_campaign = MCOMMONS_BETAS_CAMPAIGN;
  if ($form_state['betas']) {
    $betas_campaign = $form_state['betas'];
  }

  dosomething_general_mobile_commons_subscribe($you['cell'], $alphas_campaign);

  foreach ($them AS $key => $number) {
    if (dosomething_general_valid_cell($number)) {
      dosomething_general_mobile_commons_subscribe($number, $betas_campaign);
    }
  }

  // Strip any leading slashes...
  $goto = $form_state['goto'];
  if ($goto{0} == '/') {
    $goto = substr($form_state['goto'], 1);
  }

  $form_state['redirect'] = $goto;
  $_GET['redirect'] = $goto;
}

function dosomething_mobile_referral_form_submit($form, &$form_state) {
  $s = $form_state['input']['submitted'];
  $you = $s['referall_your_info'];
  $them = $s['referral_friend_info'];

  if (user_is_logged_in()) {
    global $user;
    $profile = profile2_load_by_user($user, 'main');
    if (!$profile->field_user_mobile[LANGUAGE_NONE][0]['value'] || $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] !== $you['referral_phone_number']) {
       $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] = $you['referral_phone_number'];
       $profile->save();
    }
  }

  $alphas_campaign = MCOMMONS_ALPHAS_CAMPAIGN;
  if ($form_state['alphas']) {
    $alphas_campaign = $form_state['alphas'];
  }

  $betas_campaign = MCOMMONS_BETAS_CAMPAIGN;
  if ($form_state['betas']) {
    $betas_campaign = $form_state['betas'];
  }

  dosomething_general_mobile_commons_subscribe($you['referral_phone_number'], $alphas_campaign);

  foreach ($them AS $key => $number) {
    if (dosomething_general_valid_cell($number)) {
      dosomething_general_mobile_commons_subscribe($number, $betas_campaign);
    }
  }

  // Strip any leading slashes...
  $goto = $form_state['goto'];
  if ($goto{0} == '/') {
    $goto = substr($form_state['goto'], 1);
  }

  drupal_set_message(t("Thanks for sharing stats with your friends. You've officially entered to win the scholarship. We'll be announcing the winners on Jan. 9th, so hold tight and keep your crossed 'til then! Questions? Email !e.", array('!e' => l('scholarships@dosomething.org', 'mailto:scholarships@dosomething.org'))));
  $form_state['redirect'] = $goto;
  $_GET['redirect'] = $goto;
  #drupal_set_message("Thanks for submitting.  Have a nice day!");
}
