<?php
$plugin = array(
  // Campaign title. Not used yet, but please set it.
  'title' => 'Project Clean Up',

  // Parent campaign to inherit the styling from
  //'parent' => 'footlocker_2011',

  // Add css files in the order they should be included.
  'css' => array(
    //'style.css',
  ),

  // Add javascript files in the order you would like to have them included.
  'js' => array(
  ),

  // An array of arrays indexed with 'title' and 'href'
  // These get passed to url().
  'menu' => array(
  ),
  'menu_suffix' => array(
  ),
);
