<?php

$keywords['beta-campaign-report-back'] = 'sms_flow_beta_campaign_report_back';
$keywords['can-send-mms-report-back'] = 'sms_flow_can_send_mms_report_back';
$keywords['pbj-report-back'] = 'sms_flow_pbj_report_back';
$keywords['thumbwars-report-back'] = 'sms_flow_thumbwars_report_back';
$keywords['oklahoma-report-back'] = 'sms_flow_oklahoma_report_back';
$keywords['iheartdad-report-back'] = 'sms_flow_iheartdad_report_back';
$keywords['birthdaymail-report-back'] = 'sms_flow_birthdaymail_report_back';
$keywords['spit-report-back'] = 'sms_flow_spit_report_back';

// Day 1 to Day 11 of The Hunt 2013 report backs
$keywords['hunt-enviro-report-back'] = 'sms_flow_hunt_enviro_report_back';
$keywords['hunt-homeless-report-back'] = 'sms_flow_hunt_homeless_report_back';
$keywords['hunt-literacy-report-back'] = 'sms_flow_hunt_literacy_report_back';
$keywords['hunt-bully-report-back'] = 'sms_flow_hunt_bully_report_back';
$keywords['hunt-sex-report-back'] = 'sms_flow_hunt_sex_report_back';
$keywords['hunt-health-report-back'] = 'sms_flow_hunt_health_report_back';
$keywords['hunt-discrim-report-back'] = 'sms_flow_hunt_discrim_report_back';
$keywords['hunt-animal-report-back'] = 'sms_flow_hunt_animal_report_back';
$keywords['hunt-water-report-back'] = 'sms_flow_hunt_water_report_back';
$keywords['hunt-disaster-report-back'] = 'sms_flow_hunt_disaster_report_back';
$keywords['hunt-apathy-report-back'] = 'sms_flow_hunt_apathy_report_back';