<?php

$keywords['can-send-mms-report-back'] = 'sms_flow_can_send_mms_report_back';
$keywords['birthdaymail-report-back'] = 'sms_flow_birthdaymail_report_back';
$keywords['spit-report-back'] = 'sms_flow_spit_report_back';
$keywords['survivors-report-back'] = 'sms_flow_survivors_report_back';
$keywords['fedup-report-back-1'] = 'sms_flow_fedup_report_back_1';
$keywords['fedup-report-back-2'] = 'sms_flow_fedup_report_back_2';
$keywords['50cans-report-back'] = 'sms_flow_50cans_report_back';
$keywords['ggw-report-back'] = 'sms_flow_ggw_report_back';
$keywords['momm-report-back'] = 'sms_flow_momm_report_back';