<?php

$keywords['alcoa-report-back'] = 'sms_flow_alcoa_report_back';
$keywords['beta-campaign-report-back'] = 'sms_flow_beta_campaign_report_back';
$keywords['can-send-mms-report-back'] = 'sms_flow_can_send_mms_report_back';
$keywords['sucker-report-back'] = 'sms_flow_sucker_report_back';
$keywords['tfj2013-report-back'] = 'sms_flow_tfj2013_report_back';
$keywords['pbj-report-back'] = 'sms_flow_pbj_report_back';
$keywords['thumbwars-report-back'] = 'sms_flow_thumbwars_report_back';