<?php

/**
 * @file
 * Provide a specialied slider theme function.
 */

/**
 * Implements hook_theme().
 */
function rotoslider_theme($existing, $type, $theme, $path) {
  return array(
    'rotoslider_slider' => array(
      'variables' => array('items' => NULL, 'heading' => NULL),
      'path' => $path . '/theme',
      'file' => 'theme.inc',
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function rotoslider_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'rotoslider') . '/includes',
  );
}

/**
 * Implements hook_menu().
 */
function rotoslider_menu() {
  $items = array();

  $items['rotoslider'] = array(
    'title' => 'Rotoslider',
    'page callback' => 'rotoslider_demo',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * A demo callback to display a slider.
 */
function rotoslider_demo() {
  $output = array();

  $colors = array('660000', '006600', '000066');
  $items = array();
  for ($i = 0; $i < 10; $i++) {
    $items[] = array(
      'title' => "Test $i",
      'image' => 'http://dummyimage.com/700x250/' . $colors[$i % 3] . '/fff&text=test' . $i,
      'text' => "Test $i: Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    );
  }

  $element = array(
    '#theme' => 'rotoslider_slider',
    '#items' => $items,
    '#heading' => array(
      'title' => 'Woot',
      'image' => variable_get('rotoslider_image', 'http://placekitten.com/700/250'),
      'text' => t('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nulla risus, congue sed accumsan ultricies, ultricies vitae lacus. Vestibulum bibendum egestas mi, in lobortis enim facilisis at. Nulla consequat pharetra eros in consequat.'),
    ),
  );
  //$output['element'] = $element;

  $heading = array(
    'title' => t('Explore The Menu'),
    'image' => 'http://placekitten.com/350/125',
    'text' => t('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nulla risus, congue sed accumsan ultricies, ultricies vitae lacus. Vestibulum bibendum egestas mi, in lobortis enim facilisis at. Nulla consequat pharetra eros in consequat.'),
  );
  $output['theme']['#markup'] = theme('rotoslider_slider', array('items' => $items, 'heading' => $heading));

  return $output;
}
