#! /bin/bash
# This script is for launch only

drush -y vset fb_social_base_url "http://dosomething.org"
drush -y vset fboauth_id 93836527897
drush -y vset fboauth_secret a4393ed0e0b8921da746bad0a5fe3c11
drush -y vset preprocess_css 1
drush -y vset preprocess_js 1
drush -y dis reroute_email


