#! /bin/bash
# This script is for launch only

drush @ds7 -y dis devel
drush @ds7 -y vset fb_social_base_url "http://dosomething.org"
drush @ds7 -y vset fb_social_appid 93836527897
drush @ds7 -y vset preprocess_css 1
drush @ds7 -y vset preprocess_js 1

