#! /bin/bash
# call this as ./ds-upgrade /path/to/d6-database.sql
ROOT=`drush site-alias --component=root @ds7`
# mv ${ROOT}/sites/all/modules ${ROOT}/sites/all/movedmodules
# drush @ds7 sql-drop
# drush @ds7 sqlc < $1
# drush @ds7 -y updb
# drush @ds7 -y updb
mv ${ROOT}/sites/all/movedmodules ${ROOT}/sites/all/modules
drush @ds7 -y updb
drush @ds7 vset -y theme_default bartik
drush @ds7 vset -y admin_theme seven
drush @ds7 -7 dis php
drush @ds7 -y en advanced_help admin_menu_toolbar contextual overlay rdf date date_popup date_views link location nodequeue og auto_nodetitle diff globalredirect logintoboggan pathauto token transliteration panels panels_ipe views views_ui views_data_export image node_reference user_reference field_group content_migrate page_manager location_node location_user features stylizer views_content
drush @ds7 -y content-migrate-fields

