<?php

/**
 * Implements hook_entityqueue_types().
 */
function dosomething_entityqueue_entityqueue_types() {
  $types = array();
  $types['dosomething_project'] = array(
    'label' => t('DoSomething Projects (webform submissions)'),
    'base type' => 'webform_submission_entity',
  );
  $types['dosomething_grant_application'] = array(
    'label' => t('DoSomething Grant Applications (webform submissions)'),
    'base type' => 'webform_submission_entity',
  );
  // Note, when adding a new type, entityqueue_install() must be rerun.
  // drush php-eval "include_once('sites/all/modules/entityqueue/entityqueue.install'); entityqueue_install();"
  return $types;
}
