<?php

/**
 * Implements hook_entityqueue_types().
 */
function dosomething_entityqueue_entityqueue_types() {
  $types = array();
  $types['dosomething_project'] = array(
    'label' => t('DoSomething Projects (webform submissions)'),
    'base type' => 'webform_submission_entity',
  );
  $types['dosomething_grant_application'] = array(
    'label' => t('DoSomething Grant Applications (webform submissions)'),
    'base type' => 'webform_submission_entity',
  );
  return $types;
}
