<?php

/**
 * Implements hook_entityqueue_types().
 */
function dosomething_entityqueue_entityqueue_types() {
  $types = array();
  $types['dosomething_project'] = array(
    'label' => t('DoSomething Projects (webform submissions)'),
    'base type' => 'webform_submission_entity',
  );
  $types['dosomething_grant_application'] = array(
    'label' => t('DoSomething Grant Applications (webform submissions)'),
    'base type' => 'webform_submission_entity',
  );
  // Note, when adding a new type, entityqueue_install() must be rerun.
  // drush php-eval "include_once('sites/all/modules/entityqueue/entityqueue.install'); entityqueue_install();"
  return $types;
}

/**
 * Implements hook_menu().
 */
function dosomething_entityqueue_menu() {
  $items = array();

  $base = array(
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
    'access arguments' => 'administer all queues',
  );

  $items['entityqueue/add/%/%'] = array(
    'page callback' => 'dosomething_entityqueue_add',
    'page arguments' => array(2,3),
  ) + $base;

  $items['entityqueue/swap/%/%/%'] = array(
    'page callback' => 'dosomething_entityqueue_swap',
    'page arguments' => array(2,3,4),
  ) + $base;

  $items['entityqueue/remove/%/%'] = array(
    'page callback' => 'dosomething_entityqueue_remove',
    'page arguments' => array(2,3),
  ) + $base;

  return $items;
}

function dosomething_entityqueue_add($entityqueue, $etid, $skip_goto = FALSE) {
  $entityqueue_entity = reset(entity_load('entityqueue', array($entityqueue)));
  $entity_ids = &$entityqueue_entity->eq_webform_submission_entity[LANGUAGE_NONE];

  $add = TRUE;
  foreach ($entity_ids as $key => $etid_wrapper) {
    if ($etid_wrapper['target_id'] == $etid) {
      $add = FALSE;
    }
  }
  if ($add) $entity_ids[] = array('target_id' => $etid);

  $entityqueue_entity->save();

  drupal_set_message(t('Submission !sid has been added to !entityqueue.', array('!sid' => $etid, '!entityqueue' => $entityqueue_entity->label)));

  if (!$skip_goto) drupal_goto();
}

function dosomething_entityqueue_swap($entityqueue_from, $entityqueue_to, $etid) {
  dosomething_entityqueue_remove($entityqueue_from, $etid, TRUE);
  dosomething_entityqueue_add($entityqueue_to, $etid, TRUE);
  drupal_goto();
}

function dosomething_entityqueue_remove($entityqueue, $etid, $skip_goto = FALSE) {
  $entityqueue_entity = reset(entity_load('entityqueue', array($entityqueue)));
  $entity_ids = &$entityqueue_entity->eq_webform_submission_entity[LANGUAGE_NONE];

  foreach ($entity_ids as $key => $etid_wrapper) {
    if ($etid_wrapper['target_id'] == $etid) {
      unset($entity_ids[$key]);
    }
  }
  $entityqueue_entity->eq_webform_submission_entity[LANGUAGE_NONE] = array_values($entity_ids);

  $entityqueue_entity->save();

  drupal_set_message(t('Submission !sid has been removed from !entityqueue.', array('!sid' => $etid, '!entityqueue' => $entityqueue_entity->label)));
  if (!$skip_goto) drupal_goto();
}
