<?php
/**
 * @file
 * Code for the dosomething_member_wall feature.
 */

include_once('dosomething_member_wall.features.inc');
define('DS_ISSUES_VOCAB', '5');

/**
 * Implements hook_block_info().
 */
function dosomething_member_wall_block_info() {
  $blocks['dosomething_member_wall_view'] = array(
    'info' => t('DoSomething Member Wall View Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dosomething_member_wall_block_view($delta = '') {
  switch ($delta) {
    case 'dosomething_member_wall_view':
      $block['subject'] = t('Action Update View');
      $block['content'] = dosomething_member_wall_member_wall_view_content();
      break;
  }
  return $block;
}

/**
 * Implements hook_form_alter().
 */
function dosomething_member_wall_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-member-wall-panel-pane-1') {
    // Get top level list of Issues.
    $vocab = taxonomy_get_tree(DS_ISSUES_VOCAB, 0, 1);
    foreach ($vocab as $tax) {
      $options[$tax->tid] = $tax->name;
    }
    $form['taxonomy_vocabulary_5_tid']['#options'] = array('All' => t('- Any -')) + $options;
    $form['taxonomy_vocabulary_5_tid']['#multiple'] = FALSE;
    $form['taxonomy_vocabulary_5_tid']['#size'] = NULL;
    // Get list of recent years.
    foreach (range("2008", date("Y")) as $year) {
      $years[$year] = $year;
    }
    unset($form['date_argument']);
    $form['date_argument'] = array(
      '#type' => 'select',
      '#size' => NUll,
      '#options'=> array('' => t('- Any -')) + $years,
    );
    if ($form['#info']['filter-taxonomy_vocabulary_5_tid']['value'] == 'cause') {
      $form['cause']['#options']['All'] = t('All Issues');
    }
    if ($form['#info']['filter-type_1']['value'] == 'type') {
      $form['type']['#options']['All'] = t('All Types');
    }
    if ($form['#info']['filter-submitted']['value'] == 'date_argument') {
      $form['date_argument']['#options'][''] = t('Any Year');
    }
  }
}

/**
 * Callback for master display of member_wall view.
 * Takes query string created by panel_pane_1 display and assigns them to args.
 * This is done to change the output of the member wall view exposed form.
 */
function dosomething_member_wall_member_wall_view_content() {
  $view = views_get_view('member_wall');
  $filters = $view->display['default']->display_options['arguments'];
  $args = array();
  foreach ($filters as $filter) {
    // Default to all.
    $arg = 'all';
    // If query string exists, override.
    if (isset($_GET[$filter['id']]) && $_GET[$filter['id']] != 'All' && $_GET[$filter['id']] != '') {
      // Return all children of term instead of just term.
      if ($filter['id'] == 'taxonomy_vocabulary_5_tid') {
        $kids = taxonomy_get_children($_GET[$filter['id']], DS_ISSUES_VOCAB);
        foreach ($kids as $kid) {
          $terms[] = $kid->tid;
        }
        $terms[] = $_GET[$filter['id']];
        // Deliver in term argument fashion.
        $arg = implode('+', $terms);
      }
      else {
        $arg = $_GET[$filter['id']];
      }
    }
    $args[] = $arg;
  }

  return $view->execute_display('default', $args);
}
