<?php
/**
 * @file
 * Code for the dosomething_picsforpets_general feature.
 */

include_once 'dosomething_picsforpets_general.features.inc';

// The node id for the pet submission form.
define('PICSFORPETS_PET_SUBMISSION_NID', 3);

/**
 * Implements hook_menu().
 */
function dosomething_picsforpets_general_menu() {
  $items['pics-for-pets/share/js/%'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'dosomething_picsforpets_general_share',
    'page arguments' => array(3),
  );
  return $items;
}

/**
 * Form that pops up when you click 'become a furtographer'.
 */
function dosomething_picsforpets_furtographer_dialog($form, &$form_state) {
  $form['#attached'] = array(
    'library' => array(array('system', 'ui.dialog')),
    'js' => array(
      drupal_get_path('module', 'dosomething_picsforpets_general') . '/js/dosomething-picsforpets-dialog.js',
    ),
  );

  $form['#attributes'] = array(
    'title' => 'Ready to be a fur-tographer?',
  );

  $form['ready'] = array(
    '#markup' => 'Sign up and we\'ll give you all the tools to submit a picture to the gallery.',
  );

  return $form;
}

/**
 * Implements hook_custom_theme().
 */
function dosomething_picsforpets_general_custom_theme() {
  // Use the picsforpets theme when on the pics-for-pets paths and entities of the site.
  if (arg(0) == 'pics-for-pets') {
    return 'picsforpets';
  }
  if ($submission = menu_get_object('webform_entity_pages_submission')) {
    if ($submission->nid == PICSFORPETS_PET_SUBMISSION_NID) {
      return 'picsforpets';
    }
  }
  if ($node = menu_get_object()) {
    if ($node->nid == PICSFORPETS_PET_SUBMISSION_NID) {
      return 'picsforpets';
    }
  }
}

/*
* Implements hook_ctools_plugin_directory().
*/
function dosomething_picsforpets_general_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Share (like) a webform submission on facebook.
 */
function dosomething_picsforpets_general_share($sid) {
  $_fb_app = fb_load('picsforpets');
  $fb = fb_api_init($_fb_app);
  $access_token = fb_get_token($fb);
  if (is_numeric($sid)) {
    $url = drupal_get_path_alias('webform-submission/' . $sid);
    $response = drupal_http_request('https://graph.facebook.com/' . 'http://apps.facebook.com/picsforpets/' . $url . '/likes' , array('method' => 'POST', 'data' => 'access_token=' . $access_token));
    dpm($response);
  }
  return '';
}
