<?php
/**
 * @file
 * Code for the dosomething_picsforpets_general feature.
 */

include_once 'dosomething_picsforpets_general.features.inc';

// The node id for the pet submission form.
define('PICSFORPETS_PET_SUBMISSION_NID', 3);

/**
 * Implements hook_menu().
 */
function dosomething_picsforpets_general_menu() {
  $items['pics-for-pets/share/js/%/%'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'dosomething_picsforpets_general_share',
    'page arguments' => array(3, 4),
  );
  $items['pics-for-pets/become-a-furtographer'] = array(
    'title' => t('Become a Furtographer!'),
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_picsforpets_general_furtographer_form'),
  );
  $items['pics-for-pets/ajax/thanks-for-sharing'] = array(
    'title' => t('Thanks for sharing!'),
    'access callback' => TRUE,
    'page callback' => 'dosomething_picsforpets_thanks_page_callback',
    'type' => MENU_CALLBACK,
  );
  $items['pics-for-pets/questions'] = array(
    'title' => t('Frequently Asked Questions'),
    'access callback' => TRUE,
    'page callback' => 'dosomething_picsforpets_general_questions',
  );
  return $items;
}

/**
 * Making a collapsible faq for the pics-for-pets/questions page.
 */
function dosomething_picsforpets_general_questions() {
  $page = array();
  $page['#attached'] = array(
    'js' => array(
      'misc/form.js',
      'misc/collapse.js',
    ),
  );
  $page['question1'] = array(
    '#theme' => 'fieldset',
    '#title' => t('What is pics for pets?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('Pics for Pets is a campaign by DoSomething.org to increase adoption rates in animal shelters across the country.  Armed with a camera or your smartphone, we are asking young people (25 and under) like you around the country to visit their local animal shelter to take a picture of an animal in need of a new headshot to share on the Pics for Pets Facebook or mobile app.'),
  );
  $page['question2'] = array(
    '#theme' => 'fieldset',
    '#title' => t('How do I become a fur-tographer?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('Click on “be a fur-tographer” in the Pics for Pets app, then locate your participating local shelter.  Before visiting your shelter, make sure to download the guide and watch the video of photography tips to help you along your way.  After you have taken an expert photo of an animal (or animals) at the shelter, upload the pic in the “be a fur-tographer” section and share it with your friends by clicking the “share” button.'),
  );
  $page['question3'] = array(
    '#theme' => 'fieldset',
    '#title' => t('How do I find my local shelter?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('Click on the shelter locator button in the “be a fur-tographer” section of the Pics for Pets app.  Once there, enter in your zip code to find the shelter nearest you.'),
  );
  $page['question4'] = array(
    '#theme' => 'fieldset',
    '#title' => t('What if I want to visit a different shelter?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('If you would like to visit a shelter we are not partnered with, click on the button in the lower righthand corner of the shelter locator section of the app.  Please note:  These shelters are not DoSomething.org partners, so you’ll want to reach out to them ahead of time to make sure you can come in and visit.  Make sure to tell them that you won’t need to handle any animals.'),
  );
  $page['question5'] = array(
    '#theme' => 'fieldset',
    '#title' => t('Am I allowed to handle the animals?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('For your safety, you will not be permitted to handle the animals.  When visiting the shelter, make sure that there is a volunteer present that can handle the animal for you as you take a picture of the animal.'),
  );
  $page['question6'] = array(
    '#theme' => 'fieldset',
    '#title' => t('Can I take a picture of more than one animal?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('Of course! Just be mindful that shelters are busy places and try to keep photo sessions under 30 minutes.'),
  );
  $page['question7'] = array(
    '#theme' => 'fieldset',
    '#title' => t('How do I take good photos of animals?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('Visit the “be a furtographer” section of the app and click on “get the guide.”  You’ll be able to download a great guide to help you take expert photos, as well as a video with tips on how to take the best photos.'),
  );
  $page['question8'] = array(
    '#theme' => 'fieldset',
    '#title' => t('How do I win the animals prizes?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('The more shares a picture gets, the more prizes the shelter can receive. 200 shares gets the shelter $10 for toys, 500 shares gets the shelter $30 for food and 1000 shares gets the shelter $50 for bedding (up to $10,000 in prizes).'),
  );
  $page['question9'] = array(
    '#theme' => 'fieldset',
    '#title' => t('How do I win a $5,000 scholarship?'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('Everyone that visits their local shelter and submits a picture of an animal they took will be entered to win the $10,000 scholarship.  We will be announcing the winners by December 1st.'),
  );
  $page['question10'] = array(
    '#theme' => 'fieldset',
    '#title' => t('Hey, you didn\'t answer my question!'),
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#children' => t('Sorry about that! Email animals@dosomething.org with any additional questions and Greg or April will get back to you as soon as possible.'),
  );
  return $page;
}

/**
 * Form that pops up when you click 'become a furtographer'.
 */
function dosomething_picsforpets_general_furtographer_form($form, &$form_state) {
  $form['#attributes'] = array(
    'title' => 'Ready to be a fur-tographer?',
  );
  $form['ready'] = array(
    '#markup' => '<div class="sign-up-text">Sign up and we\'ll give you all the tools to submit a picture to the gallery.</div>',
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Email:'),
    '#maxlength' => 255,

  );
  $form['cell'] = array(
    '#type' => 'textfield',
    '#title' => t('Cell:'),
    '#maxlength' => 255,
  );
  $form['kit'] = array(
    '#type' => 'checkbox',
    '#title' => t('Send me an action kit with sweet guides and supplies!'),
  );
  $form['address'] = array(
    '#prefix' => '<div id="furtographer-address">',
    '#suffix' => '</div>',
  );
  $form['address']['fields'] = array(
    '#title' => t('address'),
    '#type' => 'fieldset',
    'name' => array(
      '#type' => 'textfield',
      '#title' => t('Full Name:'),
    ),
    'street1' => array(
      '#type' => 'textfield',
      '#title' => t('Street Address:'),
    ),
    'street2' => array(
      '#type' => 'textfield',
      '#title' => t('Street Address 2:'),
    ),
    'city' => array(
      '#type' => 'textfield',
      '#title' => t('City:'),
    ),
    'state' => array(
      '#type' => 'textfield',
      '#title' => t('State'),
    ),
    'zip' => array(
      '#type' => 'textfield',
      '#title' => t('Zip'),
    ),
  );

  $form['help'] = array(
    '#markup' => '<div class="by-signing-up">' . t('By signing up you agree to the ') . l('terms and conditions', '/') . '</div><ul class="question-icon-popup"><li class="question-icon">?<ul class="question-text-popup"><li class="question-text">' . t('Enter your phone number to get weekly updates from DoSomething.org, including campaign news and chances to win prizes and scholarships. (Message and data rates may apply. Text STOP to opt-out. Email help@dosomething.org or text HELP for help.)') . '</li></ul></li></ul>',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Sign Up',
  );
  $form['#action'] = '/pics-for-pets/lets-get-started';
  $form['#attached'] = array(
    'js' => array(
      'type' => 'file',
      'data' => drupal_get_path('module', 'dosomething_picsforpets_general') . '/js/furtog-form.js',
    ),
  );
  return $form;
}

function dosomething_picsforpets_general_furtographer_form_submit($form, $form_state) {
  // TODO: send to mailchimp and campaign sign up webform.
  dpm($form_state['values']);
}

/**
 * Form that pops up after you have shared 3 pets.
 */
function dosomething_picsforpets_general_thanks_form($form, &$form_state) {
  $form['#attributes'] = array(
    'title' => t('Thanks for sharing!'),
  );
  $form['instructions'] = array(
    '#markup' => t("Enter your info and we'll send you updates on animals in the gallery"),
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Email:'),
    '#maxlength' => 255,
  );
  $form['cell'] = array(
    '#type' => 'textfield',
    '#title' => t('Cell:'),
    '#maxlength' => 255,
  );
  $form['help'] = array(
    '#markup' => t('Click submit to sign up and recieve weekly updates <a class="helptext-questionmark-popup">Enter your phone number to get weekly updates from DoSomething.org, including campaign news and chances to win prizes and scholarships. (Message and data rates may apply. Text STOP to opt-out. Email help@dosomething.org or text HELP for help.)</a>'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Callback for /pics-for-pets/ajax/thanks-for-sharing/. Renders a form and
 * then returns NULL to prevent Drupal from rendering the entire page.
 */
function dosomething_picsforpets_thanks_page_callback() {
  print render(drupal_get_form('dosomething_picsforpets_general_thanks_form'));
  return NULL;
}

/**
 * Form that pops up after you have shared 5 pets.
 */
function dosomething_picsforpets_invite_form($form, &$form_state) {
  $form['heading'] = array(
    '#markup' => t("You've helped 5 animals!"),
  );
  $form['text'] = array(
    '#markup' => t('Invite your friends to help more animals find homes!'),
  );
  include_once('plugins/content_types/invite_friends.inc');
  $form['invite'] = dosomething_picsforpets_general_content_type_render_invite()->content;
  return $form;
}

/**
 * Default validation handler for the
 * dosomething_picsforpets_general_thanks_form.
 */
function dosomething_picsforpets_general_thanks_form_validate($form, &$form_state) {
  dpm('validating');
}

/**
 * Default submit handler for the
 * dosomething_picsforpets_general_thanks_form.
 */
function dosomething_picsforpets_general_thanks_form_submit($form, &$form_state) {
  dpm('submitting');
}
/**
 * Implements hook_custom_theme().
 */
function dosomething_picsforpets_general_custom_theme() {
  // Use the picsforpets theme when on the pics-for-pets paths and entities of the site.
  if (arg(0) == 'pics-for-pets') {
    return 'picsforpets';
  }
  if ($submission = menu_get_object('webform_entity_pages_submission')) {
    if ($submission->nid == PICSFORPETS_PET_SUBMISSION_NID) {
      return 'picsforpets';
    }
  }
  if ($node = menu_get_object()) {
    if ($node->nid == PICSFORPETS_PET_SUBMISSION_NID) {
      return 'picsforpets';
    }
  }
}

/*
* Implements hook_ctools_plugin_directory().
*/
function dosomething_picsforpets_general_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Share (like) a webform submission on facebook.
 */
function dosomething_picsforpets_general_share($sid, $fbid) {
  // Update the share count on the webform submission
  module_load_include('module', 'webform_entity', 'webform_entity');
  $transaction = db_transaction();
  $submission = webform_entity_load_webform_submission($sid);
  if (!$submission) {
    watchdog('dosomething_picsforpets', 'Invalid webform submission id submitted as a share.');
    return FALSE;
  }
  $value = $submission->field_fb_app_share_count[LANGUAGE_NONE][0]['value'];
  if (!count($value)) {
    $value = 0;
  }
  $value++;
  $submission->field_fb_app_share_count[LANGUAGE_NONE][0]['value'] = $value;
  webform_entity_save_webform_submission($submission);

  // Log information about this share to the DB.
  $share = new stdClass;
  $share->entity_type = 'webform_submission_entity';
  $share->entity_id = $sid;
  $share->system_path = 'webform-submission/' . $sid;
  $share->fb_user_id = $fbid;
  $share->created = REQUEST_TIME;
  drupal_write_record('picsforpets_user_shares', $share);

  // Retrieve the total number of shares for this user.
  $user_shares = db_query("
    SELECT count(fb_user_id)
    FROM {picsforpets_user_shares}
    WHERE fb_user_id = :fbid", array(':fbid' => $fbid))
    ->fetchField();

  return drupal_json_output($user_shares);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dosomething_picsforpets_general_form_webform_client_form_3_alter(&$form, &$form_state) {
  form_load_include($form_state, 'inc', 'dosomething_picsforpets_shelters', 'dosomething_picsforpets_shelters.optionform');
  $form['#attached']['js'][] = drupal_get_path('module', 'dosomething_picsforpets_general') . '/js/shelter_popup.js';
  $form['shelter-popup'] = dosomething_picsforpets_shelters_options_form($form, $form_state);
  $form['shelter-popup']['#type'] = 'container';
  $form['shelter-popup']['#attributes'] = array(
    'id' => 'dosomething-picsforpets-shelters-options-form',
  );

  // BEGIN supression of validation errors. This stops the form from complaining
  // about missing webform form elements when we are submitting the form
  // elements for the location search.
  $form['shelter-popup']['search']['#limit_validation_errors'] = array(
    array('zip'),
  );
  $form['shelter-popup']['select-shelter']['#limit_validation_errors'] = array(
    array('results'),
    array('shelter_name'),
    array('address'),
    array('city'),
    array('state'),
    array('shelter_zip'),
    array('hours'),
  );
  $form['shelter-popup']['results']['view_more_button']['#limit_validation_errors'] = array();
  // END supression of validation errors.

  // A flag to let the ajax results know where to load.
  $form['#nested_pets_form'] = TRUE;
}

/**
 * Implements hook_preprocess_HOOK() for page.tpl.php.
 */
function dosomething_picsforpets_general_preprocess_page(&$variables) {
  $current_path = current_path();

  // Add the email address below the  questions title.
  if ($current_path == 'pics-for-pets/questions') {
    $variables['title_suffix']['dosomething_picsforpets_general_email'] = array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'questions-email',
        ),
      ),
      '#children' => t('Email us at !link', array('!link' => '<a href="mailto:picsforpets@dosomething.org">picsforpets@dosomething.org</a>')),
    );
  }

  // Add the prize details below the action guide title.
  if ($current_path == 'pics-for-pets/action-guide') {
    $variables['title_suffix']['dosomething_page-picsforpets_action_guide'] = array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'win-prizes',
        ),
      ),
      '#children' => t('And win awesome prizes along the way'),
    );
  }
}
