<?php

/**
 * Argument handler to find and set a WHERE clause based on a Facebook user ID.
 *
 * @ingroup views_argument_handlers
 */
class views_handler_argument_fb_user_id extends views_handler_argument {

  /**
   * Add a where clause to limit webform entity results based on shares by a
   * Facebook user ID.
   */
  function query($group_by = FALSE) {
//    $this->ensure_my_table();
//    $this->query->add_where(0, "$this->table_alias.$this->real_field", $this->argument);

    //
  }

}
