<?php
/**
 * @file
 * Code for the dosomething_program_short_form feature.
 */

include_once 'dosomething_program_short_form.features.inc';

/**
 * Implements hook_form_alter().
 */
function dosomething_program_short_form_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'webform_client_form_') === 0 && isset($form_state['webform_entity']) && $form_state['webform_entity']['bundle'] == 'program_short_form') {
    $form['#suffix'] = '<div id="campaign-opt-in"><span class="ctia_top">Sign up to receive weekly updates. No spam, we promise.</span><br /><span class="ctia_bottom">Msg &amp; data rates may apply. Text <strong>STOP</strong> to opt-out, <strong>HELP</strong> for help.</span></div>';
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function dosomething_program_short_form_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['dosomething_program_short_form'])) {
    $group = $implementations['dosomething_program_short_form'];
    unset($implementations['dosomething_program_short_form']);
    $implementations['dosomething_program_short_form'] = $group;
  }
}
