<?php
/**
 * @file
 * Code for the dosomething_projects_general feature.
 */

include_once('dosomething_projects_general.features.inc');

/**
 * Set amount of time for projects are editable post submission.
 */
define('DS_PROJECTS_EDITABLE_TIME', 86400);

/**
 * Implements hook_webform_submission_access().
 */
function dosomething_projects_general_webform_submission_access($node, $submission, $op, $account) {
  switch ($op) {
    case 'edit':
      // Allow users to edit project reports for 24 hrs following submission.
      $types = array(
        'project_report',
        'campaign_report_back',
      );
      static $message = NULL;
      if ($submission->uid == $account->uid && in_array($node->type, $types) && !$submission->is_draft) {
        if (REQUEST_TIME <= ($submission->submitted + DS_PROJECTS_EDITABLE_TIME)) {
          return TRUE;
        }
      }
      break;
  }
}


/**
 * Implements hook_node_access().
 */
function dosomething_projects_general_node_access($node, $op, $account) {
  if (is_object($node)) {
    // Allow node editing for 24 hours passed submission for project_updates.
    if ($node->type == 'project_update' && $op == 'update' && $node->uid == $account->uid) {
      return (REQUEST_TIME <= $node->created + DS_PROJECTS_EDITABLE_TIME) ? NODE_ACCESS_ALLOW : NODE_ACCESS_DENY;
    }
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function dosomething_projects_general_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}
