<?php
/**
 * @file
 * Code for the dosomething_projects_general feature.
 */

include_once('dosomething_projects_general.features.inc');

/**
 * Implements hook_webform_submission_access().
 */
function dosomething_projects_general_webform_submission_access($node, $submission, $op, $account) {
  switch ($op) {
    case 'edit':
      // Allow users to edit project reports for 24 hrs following submission.
      $types = array(
        'project_report',
        'campaign_report_back',
      );
      static $message = NULL;
      if ($submission->uid == $account->uid && in_array($node->type, $types) && !$submission->is_draft) {
        if (REQUEST_TIME <= ($submission->submitted + 86400)) {
          if (is_null($message)) {
            $message = t('This form will be editable until %date', array('%date' => date('m-d-Y g:ia'))); 
            drupal_set_message($message);
          }
          return TRUE;
        }  
      }
      break;
  }
}

