<?php

/**
 * @file
 * Install, update, and uninstall functions for the DoSomething subscribe module.
 */

/**
 * Initialize default Mailchimp and Mobilecommons variables.
 */
function dosomething_subscribe_update_7000() {
  variable_set('dosomething_subscribe_mailchimp_default', 'NewMembers2012');
  variable_set('dosomething_subscribe_mobilecommons_default', '155393');
}

/**
 * Initialize Mailchimp and Mobilecommons variables for Clubs.
 */
function dosomething_subscribe_update_7001() {
  variable_set('dosomething_subscribe_mailchimp_clubs', 'Clubs2012');
  variable_set('dosomething_subscribe_mobilecommons_clubs', '122361');
}

/**
 * Initialize Mailchimp and Mobilecommons variables for User registration.
 */
function dosomething_subscribe_update_7002() {
  variable_set('dosomething_subscribe_mailchimp_user_register', 'NewMembers2012');
  variable_set('dosomething_subscribe_mobilecommons_user_register', '87681');
}

/** 
 * Initalize User Profile-based Node types variable.
 */
function dosomething_subscribe_update_7003() {
  $data = array('project_report' => 'project_report');
  variable_set('dosomething_subscribe_user_profile_node_types', $data);
}
