<?php

/**
 * @file
 * Handles subscription API calls based on webform submissions (or other form submissions)
 **/

include_once 'dosomething_subscribe.update_field_values.inc';

/**
 * Actions to take when a Webform submission is made.
 *
 * @param array $node
 *   Standard node array created in the webform submission.
 * @param array $submission
 *   Array with submitted webform component values.
 */
function dosomething_subscribe_webform_submission_insert($node, $submission) {

  //drupal_set_message(print_r($submission, TRUE));

  /*
  // This is gonna be nice.
  $mailchimp = $node->field_mailchimp_group_id[LANGUAGE_NONE][0]['value'];
  $mobilecommons = $node->field_mc_optin[LANGUAGE_NONE][0]['value'];
  if ($mailchimp) {
	dosomething_subscribe_mailchimp_signup($submission->email, $mailchimp);
  }
  if ($mobilecommons) {
	dosomething_subscribe_mobilecommons_signup($submission->email, $mobilecommons);
  }
  */
}