<?php
/**
 * @file
 * Code for the Dosomething Blog feature.
 */

include_once('dosomething_blog.features.inc');

/**
* Implementation of hook_ctools_plugin_directory().
*/
function dosomething_blog_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dosomething_blog_form_views_exposed_form_alter(&$form, $form_state) {
  if ($form['#id'] == 'views-exposed-form-blog-center-panel-pane-3') {
    $form['field_blog_type_tid']['#options']['All'] = $form['#info']['filter-field_blog_type_tid']['label'];
    $form['taxonomy_vocabulary_5_tid']['#options']['All'] = $form['#info']['filter-taxonomy_vocabulary_5_tid']['label'];
  }
}
