<?php

$plugin = array(
  'title' => t('Campaign'),
  'category' => t('Dosomething'),
  'icon' => 'campaign.png',
  'theme' => 'dosomething_panels_campaign',
  'css' => 'campaign.css',
  'regions' => array(
    'top-first-top-first' => t('Top Left'),
    'top-first-top-second' => t('Top Right'),
    'top-first-bottom' => t('Main'),
    'top-second' => t('Right'),
    'middle-first' => t('Middle Left'),
    'middle-second' => t('Middle Center'),
    'middle-third' => t('Middle Right'),  
    'low-full' => t('Full Row'),  
    'bottom-first' => t('Bottom Left'),
    'bottom-second' => t('Bottom Right'),
  ),
);




