<?php

$plugin = array(
  'title' => t('Campaign'),
  'category' => t('Dosomething'),
  'icon' => 'campaign.png',
  'theme' => 'dosomething_panels_campaign',
  'css' => 'campaign.css',
  'regions' => array(
    'logo' => t('Logo'),
    'mini-info' => t('Mini Quick Info'),
    'social' => t('Social'),
    'sign-up' => t('Sign Up'),
    'stats' => t('Stats'),
    'quick-info' => t('Full Quick Info'),
    'psa' => t('PSA or Image'),
    'flexible-top' => t('Top Flexible Region'),
    'flexible-mid' => t('Middle Flexible Region'),
    'flexible-bot' => t('Bottom Flexible Region'),
    'logos' => t('Logos'),
  ),
);




