<?php
/**
 * @file
 * Code for the DoSomething Project feature.
 */

include_once 'dosomething_project.features.inc';

/**
 * Implements hook_theme().
 */
function dosomething_project_theme($existing, $type, $theme, $path) {
	// Defined alphabetically to promote sanity.
	 return array(
    'project_section_action_items' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_action_items',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_cta' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_cta',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_faq' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_faq',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_gallery' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_gallery',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_header' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_header',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_prizes' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_prizes',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_project_info' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_project_info',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_project_profiles' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_project_profiles',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_sms_example' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_sms_example',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
    'project_section_sms_referral' => array(
      'path' => $path . '/templates',
      'template' => 'project_section_sms_referral',
      'arguments' => array(
      	'node' => NULL, 
      ),
    ),
  );
}

/**
 * Return values in a node's field_collection.
 */
function dosomething_project_get_field_collection_values($node, $field_collection_name, $child_field_prefix) {
  // Field collecitons with no images:
  $no_image_fc = array('project_info_items');
  $field_collection_fields = field_get_items('node', $node, $field_collection_name);
  // Extract the field collection item ids:
  $ids = array();
  foreach ($field_collection_fields as $fc_field) {
    $ids[] = $fc_field['value'];
  }
  $items = field_collection_item_load_multiple($ids);
  $i = 0;
  foreach($items as $item) {
  	if (!in_array($field_collection_name, $no_image_fc)) {
	    $image = field_get_items('field_collection_item', $item, 'field_' . $child_field_prefix . '_image');
	    $values[$i]['image']['uri'] = file_create_url($image[0]['uri']);
	    $values[$i]['image']['alt'] = $image[0]['alt'];
    }
    $title = field_get_items('field_collection_item', $item, 'field_' . $child_field_prefix . '_title');
    $values[$i]['title'] = $title[0]['safe_value'];
    $copy = field_get_items('field_collection_item', $item, 'field_' . $child_field_prefix . '_copy');
    $values[$i]['copy'] = $copy[0]['safe_value'];
    $i++;
  }
  return $values;
}