<?php

/**
 * Implements hook_webform_component_info().
 */
function webform_quiz_webform_component_info() {
  $components = array();

  $components['quiz_question'] = array(
    'label' => t('Quiz question'),
    'description' => t('A question to be scored for a quiz.'),
    'features' => array(
      'description' => FALSE,
      'title_display' => FALSE,
      'title_inline' => FALSE,
      'default_value' => FALSE,
    ),
    'file' => 'webform_quiz.component.inc',
  );

  return $components;
}

/**
 * Implements hook_form_alter().
 */
function webform_quiz_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_configure_form') {

    $field_limit = 8;
    $filler = range(0, $field_limit);
    unset($filler[0]);

    $form['role_control']['#weight'] = -2;

    $form['quiz_enable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable quiz feature'),
      '#weight' => -3,
    );

    $form['quiz'] = array(
      '#type' => 'fieldset',
      '#title' => t('Quiz Options'),
      '#description' => t('Enter the URL, internal or external, to redirect to when a given numbered response is chosen most frequently. In other words, if response 1 is chosen the most number of times, we will redirect them to the URL below for response 1. Additional fields will show up, up to 8, after entering a value.'),
      '#collapsible' => TRUE,
      '#weight' => -3,
      '#states' => array(
        'visible' => array(
          ':input[name="quiz_enable"]' => array('checked' => TRUE),
        ),
      ),
    );

    foreach ($filler as $int) {
      $form['quiz']['response_redirect_' . $int] = array(
        '#type' => 'textfield',
        '#title' => t('Redirect URL: Response') . ' ' . $int,
        '#states' => array(
          'visible' => array(
            ':input[name="response_redirect_'.($int-1).'"]' => array('empty' => FALSE),
          ),
        ),
      );
    }
    unset($form['quiz']['response_redirect_1']['#states']);

    $form['#valudate'][] = 'webform_quiz_webform_configure_validate';
    $form['#submit'][] = 'webform_quiz_webform_configure_submit';
  }
}
