<?php

/**
 * @file
 * Custom code relating to PicsForPets pet creation and display.
 */

/**
 * Implements hook_menu().
 */
function dosomething_picsforpets_animals_menu() {
  $items['pics-for-pets/carousel/js/%'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'dosomething_picsforpets_animals_wings',
    'page arguments' => array(3),
  );
  return $items;
}

/**
 * Implements webform_submission_render_alter().
 */
function dosomething_picsforpets_animals_webform_submission_render_alter(&$renderable) {
  // Add carousel javascript to displays of pet profiles.
  $node = $renderable['#node'];
  if ($node->type == 'fb_app_data_gathering_form' && $node->title == 'Pet Picture') { // TODO: check for specific node id once we know one; the title can change.
    drupal_add_js(drupal_get_path('module', 'dosomething_picsforpets_animals') . '/js/picsforpets-carousel.js');
    drupal_add_js(array('picsforpetsAnimals' => array('sid' => $renderable['#submission']->sid)), 'setting');
    // Total number of available pet submissions.
    // TODO: limit to correct node results.
    $total = db_query("SELECT COUNT(sid) FROM webform_submissions")->fetchField();
    drupal_add_js(array('picsforpetsAnimals' => array('total' => $total)), 'setting');
  }
}

/**
 * Menu callback.
 * Return 10 items for the 'wings' on the pet carousel.
 */
function dosomething_picsforpets_animals_wings($sid, $offset = 0) {
  // TODO: order by sharing desc and limit to correct node results.
  $sids = db_query_range("SELECT sid FROM webform_submissions WHERE sid <> :sid", $offset, 8, array(':sid' => $sid))->fetchCol();
  if (!$offset) {
    array_unshift($sids, $sid);
    $i = 0;
  }
  else {
    $i = $offset + 1;
  }
  foreach ($sids as $sid) {
    $wrapper = entity_metadata_wrapper('webform_submission_entity', $sid);
    $submission = new stdClass();
    $submission->sid = $sid;
    $path = $wrapper->field_pfp_webform_image->value();
    $submission->image = theme('image', array('path' => $path['uri']));
    if ($i % 2) {
      $submissions[-1 * ($i + 1 ) / 2] = $submission;
    }
    else {
      $submissions[$i / 2] = $submission;
    }
    $i++;
  }
  drupal_json_output($submissions);
}
