<?php

/**
 * @file
 * Provides a views style plugin for DoSomething Apps Grid.
 */

/**
 * Implements hook_views_api().
 */
function dosomething_apps_grid_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'dosomething_apps_grid') . '/includes',
  );
}

/**
 * Implements hook_theme().
 */
function dosomething_apps_grid_theme($existing, $type, $theme, $path) {
  return array(
    'dosomething_apps_grid' => array(
      'render element' => 'element',
      'file' => 'theme.inc',
      'path' => $path . '/includes',
    ),
  );
}
