<?php

/**
 * @file
 * The DoSomething API is a library that connects with DoSomething.org's datastore.
 * Functions within this library allow us to connect with users' information, posts,
 * comments, articles, etc.
 *
 * @author Michael Chittenden (mchittenden@dosomething.org)
 */

/**
 *  Log in a user.  Assuming $e_or_c is a valid email or cell phone
 *  number of a DoSomething.org member:
 *  @code
 *    dosomething_api_user_log_in('email@dosomething.org');
 *  @endcode
 *
 *  @param string $name
 *    The person's first name.
 *
 *  @param string $contact
 *    The email or cell phone number of the person.
 *
 *  @param string $password
 *    The user's password.
 *
 *  @param array $buckets
 *    (Optional) array of buckets for MailChimp / Mobile Commons integration.
 */
function dosomething_api_create_or_log_in_user($name = '', $contact = '', $password = '', $buckets = array('email' => '', 'mobile' => '')) {
  // Only run this if a user is not logged in.
  if (user_is_logged_in()) {
    return;
  }

  $account = dosomething_api_user_log_in($contact);

  if (empty($account)) {
    $u = array(
      'name' => $name,
      'password' => $password
    );

    if (valid_email_address($contact)) {
      $u['email'] = $contact;
    }
    elseif (dosomething_general_valid_cell($contact)) {
      $u['mobile'] = $contact;
    }

    $account = dosomething_api_user_create($u);

    if (!empty($account)) {
      // Run these *after* we know a user was successfully created.
      if (isset($u['email']) && !empty($buckets['email'])) {
        dosomething_general_mailchimp_subscribe($u['email'], $buckets['email']);
      }
      elseif (isset($u['mobile']) && !empty($buckets['mobile'])) {
        dosomething_general_mobile_commons_subscribe($u['mobile'], $buckets['mobile']);
      }

      dosomething_api_user_log_in($contact);
    }
  }
}

/**
 *  Log in a user.
 *
 *  @param string $e_or_c
 *    A user's email or cell.  Will check against a formatted (e.g. with dashes)
 *    and unformatted version of a mobile number, if appropriate.
 *
 *  @param int $uid
 *    (Optional) The user ID belonging to the account in question.
 *
 *  @param object $account
 *    If available, the account object for the user.  If unspecified, will get the
 *    object from dosomething_api_user_lookup() function.
 *
 *  @see dosomething_api_user_lookup()
 */
function dosomething_api_user_log_in($e_or_c, $uid = 0, $account = array()) {
  if (!$uid) {
    $account = dosomething_api_user_lookup($e_or_c);
  }
  elseif ($uid > 0) {
    $account->uid = $uid;
  }

  if (!empty($account)) {
  	$u = array('uid' => $account->uid);
  	user_login_submit(array(), $u);
  }

  return $account;
}

/**
 * Load up the related user given and email or cell phone value.
 *
 * @param $value
 *   An email or cell phone value.
 * @return
 *  Either FALSE or the loaded user account.
 */
function dosomething_api_user_lookup($value) {
  $account = FALSE;
  if (valid_email_address($value)) {
    $account = user_load_by_mail($value);
  }
  else if ($number = dosomething_general_clean_cell_number($value)) {
    $account = dosomething_general_find_user_by_cell($number);
  }
  return $account;
}

function dosomething_api_user_fetch_data($data = array('account' => array(), 'profile' => array())) {
  global $user;
  if (!$user->uid) {
    return false;
  }

  $return = array();
  if (isset($data['account'])) {
    foreach ($data['account'] AS $field) {
      if (isset($user->{$field})) {
        $return[$field] = $user->{$field};
      }
    }
  }
  if (isset($data['profile'])) {
    $p = profile2_load_by_user($user, 'main');
    foreach ($data['profile'] AS $field => $alias) {
      if (isset($p->{$field}[LANGUAGE_NONE][0]['value'])) {
        $return[($alias ? $alias : $field)] = $p->{$field}[LANGUAGE_NONE][0]['value'];
      }
    }
  }

  return $return;
}

function dosomething_api_user_create($info = array('name' => '', 'email' => '', 'mobile' => ''), $login = FALSE) {
  // Start the account class.
  $account = new stdClass;

  // If we don't have a name, default to "Guest user"
  if (empty($info['name'])) {
    $info['name'] = t('Guest user');
  }

  $suffix = 0;
  $account->name = $info['name'];
  // If we can find users with that exact name, append a number to the end.
  while (user_load_by_name($account->name)) {
     $suffix++;
     $account->name = $info['name'] . '-' . $suffix;
  }

  // Create a random password for the user.
  if (!$this['password']) {
    $pass = user_password(6);
  }
  else {
    $pass = $this['password'];
  }
  require_once('includes/password.inc');
  $hashed_pass = user_hash_password($pass);
  $account->pass = $hashed_pass;

  // Set the email address (or "fake" email for mobile)
  $account->mail = ($info['email'] ? $info['email'] : $info['mobile'] . '@mobile');
  // The user account is activated.
  $account->status = 1;

  // Save the user.
  $account = user_save($account);

  // Load a profile object for the user.
  $profile_values = array('type' => 'main');
  $profile = profile2_create($profile_values);
  $profile->uid = $account->uid;

  // If we have the user's phone number, set that.
  if (!empty($info['mobile'])) {
   $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] = $info['mobile'];
  }
  // If they have a real first name, set that.
  if ($info['name'] != 'Guest user') {
     $profile->field_user_first_name[LANGUAGE_NONE][0]['value'] = $info['name'];
  }

  // Try and save the profile and set a message that we did so...
  try {
    profile2_save($profile);
    watchdog('Api', t('A user was successfully created with the email / cell ' . ($info['email'] ? $info['email'] : $info['mobile'])));
  }
  // ...or throw an exception saying we failed.
  catch (Exception $e) {
    throw new ApiException(t('Sorry, there was a problem creating the account.'));
  }

  // Set the profile object as a sub-object of user.
  $account->profile = $profile;

  return $account;
}

/**
 *  Checks whether a password for a given user is a valid password.
 *
 *  @param string $contact
 *    Either the email or the cell phone # of the account in question.
 *
 *  @param string $password
 *    The proposed password for that account.
 *
 *  @return bool
 *    True if the password is correct, else false.
 */
function dosomething_api_valid_password($contact, $password) {
  require_once DRUPAL_ROOT . '/includes/password.inc';
  if ($account = dosomething_api_user_lookup($contact)) {
    if (!user_check_password($password, $account)) {
      return FALSE;
    }
    else {
      return TRUE;
    }
  }

  return TRUE;
}
