<?php

function dosomething_feeds_menu() {
  $items = array();
  $items['news/feed'] = array(
    'title' => 'DoSomething.org News Feed',
    'page callback' => 'dosomething_feeds_news',
    'access callback' => TRUE,
    'description' => 'DoSomething.org News',
    'type' => MENU_CALLBACK,
  );
  /*
  $items['cgg/rss'] = array(
    'title' => 'Celebs Gone Good',
    'page callback' => 'dosomething_feed_cgg',
    'access callback' => TRUE,
    'description' => 'News on the latest Celebs Gone Good',
    'type' => MENU_CALLBACK,
  );
  */
  return $items;
}

function dosomething_feeds_theme() {
  return array(
    'dosomething_feed' => array(
      'tempalte' => 'feed',
      'arguments' => array(
        'path' => '',
        'items' => '',
      ),
    ),
    'dosomething_feed_item' => array(
      'tempalte' => 'feed-item',
      'arguments' => array(
        'path' => '',
        'items' => '',
      ),
    ),
  );
}



// TODO: MOVE ME TO AN INCLUDE!!!
function dosomething_feeds_get_view() {
  $view = new view;
  $view->name = 'dosomething_news_feeds';
  $view->description = 'The DoSomething.org News Box';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'DoSomething.org News Box';
  $view->core = 7;
  $view->api_version = '3.0-alpha1';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Dosomething.org News Box';
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['query_comment'] = FALSE;
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['hide_empty'] = 0;
  $handler->display->display_options['row_options']['default_field_elements'] = 0;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = 1;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<title>[title]</title>';
  $handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['title']['alter']['external'] = 0;
  $handler->display->display_options['fields']['title']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['title']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->display_options['fields']['title']['hide_alter_empty'] = 0;
  $handler->display->display_options['fields']['title']['link_to_node'] = 0;
  /* Field: Content: Path */
  $handler->display->display_options['fields']['path']['id'] = 'path';
  $handler->display->display_options['fields']['path']['table'] = 'node';
  $handler->display->display_options['fields']['path']['field'] = 'path';
  $handler->display->display_options['fields']['path']['label'] = '';
  $handler->display->display_options['fields']['path']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['path']['alter']['text'] = '<link>http://dosomething.org[path]</link>';
  $handler->display->display_options['fields']['path']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['path']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['path']['alter']['external'] = 0;
  $handler->display->display_options['fields']['path']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['path']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['path']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['path']['alter']['word_boundary'] = 0;
  $handler->display->display_options['fields']['path']['alter']['ellipsis'] = 0;
  $handler->display->display_options['fields']['path']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['path']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['path']['alter']['html'] = 0;
  $handler->display->display_options['fields']['path']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['path']['element_default_classes'] = 0;
  $handler->display->display_options['fields']['path']['hide_empty'] = 0;
  $handler->display->display_options['fields']['path']['empty_zero'] = 0;
  $handler->display->display_options['fields']['path']['hide_alter_empty'] = 0;
  $handler->display->display_options['fields']['path']['absolute'] = 0;
  /* Field: Content: Post date */
  $handler->display->display_options['fields']['created']['id'] = 'created';
  $handler->display->display_options['fields']['created']['table'] = 'node';
  $handler->display->display_options['fields']['created']['field'] = 'created';
  $handler->display->display_options['fields']['created']['label'] = '';
  $handler->display->display_options['fields']['created']['alter']['alter_text'] = 1;
  $handler->display->display_options['fields']['created']['alter']['text'] = '<pubDate>[created]</pubDate>';
  $handler->display->display_options['fields']['created']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['created']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['created']['alter']['external'] = 0;
  $handler->display->display_options['fields']['created']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['created']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['created']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['created']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['created']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['created']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['created']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['created']['alter']['html'] = 0;
  $handler->display->display_options['fields']['created']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['created']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['created']['hide_empty'] = 0;
  $handler->display->display_options['fields']['created']['empty_zero'] = 0;
  $handler->display->display_options['fields']['created']['hide_alter_empty'] = 0;
  $handler->display->display_options['fields']['created']['date_format'] = 'short';
  /* Field: Content: Body */
  $handler->display->display_options['fields']['body']['id'] = 'body';
  $handler->display->display_options['fields']['body']['table'] = 'field_data_body';
  $handler->display->display_options['fields']['body']['field'] = 'body';
  $handler->display->display_options['fields']['body']['label'] = '';
  $handler->display->display_options['fields']['body']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['body']['alter']['text'] = '[body]]]></description>';
  $handler->display->display_options['fields']['body']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['body']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['body']['alter']['external'] = 0;
  $handler->display->display_options['fields']['body']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['body']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['body']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['body']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['body']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['body']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['body']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['body']['alter']['html'] = 0;
  $handler->display->display_options['fields']['body']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['body']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['body']['hide_empty'] = 0;
  $handler->display->display_options['fields']['body']['empty_zero'] = 0;
  $handler->display->display_options['fields']['body']['hide_alter_empty'] = 0;
  $handler->display->display_options['fields']['body']['type'] = 'text_summary_or_trimmed';
  $handler->display->display_options['fields']['body']['settings'] = array(
    'trim_length' => '600',
  );
  $handler->display->display_options['fields']['body']['field_api_classes'] = 0;
  /* Field: Content: File attachments */
  $handler->display->display_options['fields']['upload']['id'] = 'upload';
  $handler->display->display_options['fields']['upload']['table'] = 'field_data_upload';
  $handler->display->display_options['fields']['upload']['field'] = 'upload';
  $handler->display->display_options['fields']['upload']['label'] = '';
  $handler->display->display_options['fields']['upload']['alter']['alter_text'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['make_link'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['absolute'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['external'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['replace_spaces'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['trim_whitespace'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['nl2br'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['word_boundary'] = 1;
  $handler->display->display_options['fields']['upload']['alter']['ellipsis'] = 1;
  $handler->display->display_options['fields']['upload']['alter']['strip_tags'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['trim'] = 0;
  $handler->display->display_options['fields']['upload']['alter']['html'] = 0;
  $handler->display->display_options['fields']['upload']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['upload']['element_default_classes'] = 1;
  $handler->display->display_options['fields']['upload']['hide_empty'] = 1;
  $handler->display->display_options['fields']['upload']['empty_zero'] = 0;
  $handler->display->display_options['fields']['upload']['hide_alter_empty'] = 0;
  $handler->display->display_options['fields']['upload']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['upload']['group_rows'] = 1;
  $handler->display->display_options['fields']['upload']['delta_offset'] = '0';
  $handler->display->display_options['fields']['upload']['delta_reversed'] = 0;
  $handler->display->display_options['fields']['upload']['field_api_classes'] = 0;
  /* Field: Content: Issues */
  $handler->display->display_options['fields']['taxonomy_vocabulary_5']['id'] = 'taxonomy_vocabulary_5';
  $handler->display->display_options['fields']['taxonomy_vocabulary_5']['table'] = 'field_data_taxonomy_vocabulary_5';
  $handler->display->display_options['fields']['taxonomy_vocabulary_5']['field'] = 'taxonomy_vocabulary_5';
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 0;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'chatterbox' => 'chatterbox',
  );
  return $view;
}

function dosomething_feeds_news() {
  //drupal_add_http_header('Content-Type: text/xml; charset=utf-8');
  $view = dosomething_feeds_get_view();
  $view->execute();
  $results = $view->result;
  $output = array(
    '#theme' = 'dosomething_feed'
  );
  foreach ($results as $result) {
    $output['items'][] = array(
      '#data' => $result,
      '#theme' => 'dosomething_feed_item',
    );
  }
  return 'funk';
}
