<?php
/**
 * @file
 * dosomething_campaign.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function dosomething_campaign_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_month_day';
  $strongarm->value = 'n/j';
  $export['date_format_month_day'] = $strongarm;

  return $export;
}
