<?php

/**
 * @file
 * Code for the Dosomething Campaign feature.
 */

include_once('dosomething_campaign.features.inc');
// Include Campaign-specific form callback functions:
include_once('includes/kiva.inc');
include_once('includes/momm.inc');
include_once('includes/tfj.inc');

/**
 * Implements hook_ctools_plugin_type().
 */
/*
function dosomething_campaign_ctools_plugin_type() {
  return array(
    'signup_data_modal' => array(
      'cache' => FALSE,
    ),
  );
}
*/

/**
 * Implements hook_ctools_plugin_directory().
 */
function dosomething_campaign_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_theme().
 */
function dosomething_campaign_theme($existing, $type, $theme, $path) {
  return array(
    'kiva_confirmation' => array(
      'path' => $path . '/templates',
      'template' => 'kiva_confirmation',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function dosomething_campaign_block_info() {
  $blocks = array();
  $blocks['kiva_signup'] = array(
    'info' => t('Kiva Campaign Signup Form'),
  );
  $blocks['kiva_confirmation'] = array(
    'info' => t('Kiva Campaign Signup Confirmation'),
  );
  $blocks['tfj_signup_button'] = array(
    'info' => t('TFJ Signup Button (for Testing)'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dosomething_campaign_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'kiva_signup':
      $block['content'] = drupal_render(drupal_get_form('dosomething_campaign_beta_signup_form', 729307));
      break;
    case 'kiva_confirmation':
      $block['content'] = theme('kiva_confirmation');
      break;
    case 'tfj_signup_button':
      $block['content'] = dosomething_campaign_tfj_get_signup_button();
      break;
  }
  return $block;
}

/**
 * Handles a campaign signup via login through campaign gate.
 *
 * @param $account
 *  Account object of user who logged in.
 * @param $node
 *  Node object of campaign user is signing up for.
 */
function dosomething_campaign_signup($account, $node) {
  $nid = $node->nid;
  $user_signed_up = dosomething_signups_is_user_signed_up($account->uid, $nid);
  if (!$user_signed_up) {
    dosomething_signups_insert_signup($account->uid, $nid);
    $email = $account->mail;
    $user2 = profile2_load_by_user($account, 'main');
    // Mailchimp signup:
    $mailchimp = $node->field_mailchimp_group_id[LANGUAGE_NONE][0]['value'];
    if ($mailchimp && !empty($mailchimp)) {
      dosomething_subscribe_mailchimp_signup($email, $mailchimp);
    }
    // Mobilecommons signup:
    $mobilecommons = $node->field_mc_optin[LANGUAGE_NONE][0]['value'];
    if ($mobilecommons && !empty($mobilecommons)) {
      $cell = '';
      $user2 = profile2_load_by_user($account, 'main');
      $cell = field_get_items('profile2', $user2, 'field_user_mobile');
      $cell = $cell[0]['value'];
      if (!empty($cell)) {
        $response = dosomething_general_mobile_commons_subscribe($cell, $mobilecommons);
        watchdog('dosomething_campaign', 'cell = ' . $cell . ' opt_in = ' . $mobilecommons . ' response = ' . print_r($response, TRUE));
      }
    }
    // Mandrill mail:
    if (module_exists('dosomething_mandrill')) {
      $mandrill = $node->field_mandrill_key[LANGUAGE_NONE][0]['value'];
      $fname = field_get_items('profile2', $user2, 'field_user_first_name');
      $message['FNAME'] = $fname[0]['value'];
      if ($mandrill && !empty($mandrill)) {
        dosomething_mandrill_dispatch($email, $mandrill, $message);
      }
    }
  }
}

/**
 * Inserts given array $data values as a Campaign Signup Address List webform submission.
 *
 * @param array $data
 *   An array of user information and address values from a campaign signup form.
 *
 * @return
 *   The submission sid of the isnerted webform submission.
 *
 */
function dosomething_campaign_submit_signup_address($data) {
  // Just hardcodin' some webform nid's over here.
  $node = node_load(variable_get('campaign_signup_address_list_nid', 731111));
  $submission = new stdClass;
  $submission->uid = $data['uid'];
  $submission->submitted = REQUEST_TIME;
  $submission->remote_addr = ip_address();
  $submission->is_draft = FALSE;
  // Just hardcodin' some webform component nid's over here.
  $submission->data = array(
    1 => array('value' => array($data['nid'])),
    2 => array('value' => array($data['address1'])),
    3 => array('value' => array($data['address2'])),
    4 => array('value' => array($data['city'])),
    5 => array('value' => array($data['state'])),
    6 => array('value' => array($data['zip'])),
    7 => array('value' => array($data['name'])),
    // Not a typo, component 8 was deleted from the webform.
    9 => array('value' => array($data['email'])),
  );
  module_load_include('inc', 'webform', 'includes/webform.submissions');
  return webform_submission_insert($node, $submission);
}
