<?php

/**
 * @file
 * Custom functionality relating to user registration and login.
 */

/**
 * Implements hook_menu().
 */
function dosomething_login_menu() {
  $items = array();
  $items['mobile-signup'] = array(
    'title' => 'Mobile Signup',
    'description' => 'Sign up URL to which mobile commons submits sign up requests to us.',
    'page callback' => 'dosomething_login_mobile_signup',
    'access callback' => 'dosomething_login_mobile_signup_access',
  );
  $items['user/registration'] = array(
    'title' => 'Registration',
    'description' => 'Sign up URL to which mobile commons submits sign up requests to us.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_login_register_popup_form'),
    'access callback' => 'user_register_access',
    'type' => MENU_CALLBACK,
  );
  $items['dosomething/under-13/permission/%/%/%'] = array(
    'title' => 'Parental Permission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_login_parent_permission_page', 3, 4, 5),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['dosomething/under-13/parent-consent-email'] = array(
    'title' => 'Parental Permission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dosomething_login_parent_permission_email_form'),
    'access callback' => 'dosomething_parent_consent_email_access',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function dosomething_login_menu_alter(&$items) {
  // Remove the default user registration page in favor of our custom registration.
  unset($items['user/register']);
}

/**
 * Implements hook_block_info().
 */
function dosomething_login_block_info() {
  $blocks['become_member'] = array(
    'info' => t('Become a Member'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dosomething_login_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'become_member':
      global $user;
      if (!$user->uid) {
        if ((arg(0) != 'user' || arg(1) != 'registration')) {
          $block['subject'] = t('Become a Member');
          $block['content'][] = drupal_get_form('dosomething_login_register_block');
          $block['content'][] = drupal_get_form('dosomething_login_register_popup_form');
        }
      }
      else {
        $block['subject'] = '';
        $block['content'] = dosomething_login_member_block();
      }
      break;
  }
  return $block;
}

/**
 * Implements hook_mail().
 */
function dosomething_login_mail($key, &$message, $params) {
  switch ($key) {
    case 'dosomething-parent-email':
      $params['full_name'] = dosomething_login_get_user_full_name($params['account']);
      $message['subject'] = t('Permissions for %name', array('%name' => $params['full_name']));
      $message['body'][] = drupal_html_to_text(theme('dosomething_login_parent_email', $params));
      $message['headers']['Content-Type'] = 'text/html; charset=utf-8';
      break;
    case 'dosomething-parent-permission-granted-email':
      $params['full_name'] = dosomething_login_get_user_full_name($params['account']);
      $message['subject'] = t('Permission Granted');
      $message['body'][] = drupal_html_to_text(theme('dosomething_login_parent_permission_granted_email', $params));
      $message['headers']['Content-Type'] = 'text/html; charset=utf-8';
      break;
    case 'dosomething-parent-permission-denied-email':
      $params['full_name'] = dosomething_login_get_user_full_name($params['account']);
      $message['subject'] = t('Permission Denied');
      $message['body'][] = drupal_html_to_text(theme('dosomething_login_parent_permission_denied_email', $params));
      $message['headers']['Content-Type'] = 'text/html; charset=utf-8';
      break;
  }
}

/**
 * Implements hook_theme().
 */
function dosomething_login_theme() {
  return array(
    'dosomething_login_member_lightbox' => array(
      'path' => drupal_get_path('module', 'dosomething_login') . '/templates',
      'template' => 'dosomething-login-member-lightbox',
    ),
    'dosomething_login_parent_email' => array(
      'path' => drupal_get_path('module', 'dosomething_login') . '/templates',
      'arguments' => array('full_name' => NULL),
      'template' => 'dosomething-login-parent-email',
    ),
    'dosomething_login_parent_permission_granted_email' => array(
      'path' => drupal_get_path('module', 'dosomething_login') . '/templates',
      'arguments' => array('full_name' => NULL),
      'template' => 'dosomething-login-parent-permission-granted-email',
    ),
    'dosomething_login_parent_permission_denied_email' => array(
      'path' => drupal_get_path('module', 'dosomething_login') . '/templates',
      'arguments' => array('full_name' => NULL),
      'template' => 'dosomething-login-parent-permission-denied-email',
    ),
  );
}

/**
 * Implements hook_cron().
 */
function dosomething_login_cron() {
  // TODO: Only run every few hours?
  dosomething_login_update_accounts_under_13();
  dosomething_login_clear_old_accounts();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dosomething_login_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;
  if (!dosomething_login_user_has_parental_consent($user->uid)) {
    // Note: Give a user parental consent if they are over 13
    // so that they don't get stuck not being able to edit their
    // account by changing their birthdate.
    dosomething_login_set_parental_consent_message();
    drupal_goto('user');
  }
}

/**
 * Implements hook_form_alter().
 */
function dosomething_login_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node_edit_form']) && $form['#node_edit_form']) {
    $node_types = array(
      'campaign_report_back',
      'campaign_sign_up',
      'grant_application',
      'scholarship_application',
      'action_guide',
      'project_report',
    );
    // Users without parental consent should be able to see this
    // but not be able to do anything with it.
    if (in_array($form['type']['#value'], $node_types)) {
      global $user;
      if (!dosomething_login_user_has_parental_consent($user->uid)) {
        dosomething_login_set_parental_consent_message();
        drupal_goto();
      }
    }
  }
}

/**
 * The form for the 'Become a Member' block.
 */
function dosomething_login_register_popup_form($form, &$form_state) {
  $form['#validate'][] = 'dosomething_login_register_block_validate';
  $form['#submit'][] = 'dosomething_login_register_block_submit';
  $form['#attached'] = array(
    'js' => array(
      // TODO: Only add on user/registration page.
      drupal_get_path('module', 'dosomething_login') . '/js/dosomething-login-registration-lightbox.js',
    ),
  );

  $query = drupal_get_destination();
  $query['destination'] = $query['destination'] == 'user/registration' ? 'front' : $query['destination'];
  $form['#action'] = url($_GET['q'], array('query' => drupal_get_destination()));
  $form['#action'] = url('user/registration', array('query' => $query));

  $form['title_text'] = array(
    '#type' => 'item',
    '#title' => t('You\'re almost there.'),
    '#description' => t('Fill out the rest of the informationbelow and you\'ll be a member in no time.'),
  );
  $form['name'] = array(
    'first_name' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('First Name'),
        'class' => array('dosomething-original-value'),
      ),
      '#size' => 9,
    ),
    'last_name' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('Last Name'),
        'class' => array('dosomething-original-value'),
      ),
      '#size' => 9,
    ),
  );
  $form['cell_or_email'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Cell Number or E-mail'),
      'class' => array('dosomething-original-value'),
    ),
    '#size' => 20,
  );
  $form['birthday'] = array(
    'over_13' => array('#markup' => '<div class="age-question">' . t('Birthday') . '</div>'),
    'month' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('mm'),
        'class' => array('dosomething-original-value'),
      ),
      '#size' => 2,
      '#maxlength' => 2,
    ),
    'day' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('dd'),
        'class' => array('dosomething-original-value'),
      ),
      '#size' => 2,
      '#maxlength' => 2,
    ),
    'year' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('yyyy'),
        'class' => array('dosomething-original-value'),
      ),
      '#size' => 4,
      '#maxlength' => 4,
    ),
  );

  $form['parent_email_message'] = array(
    '#type' => 'item',
    '#title' => t('What a Rock Star!'),
    '#description' => t('Since you\'re under the age of 13, you\'ll need to get a parent or guradian\'s permission.'),
    '#prefix' => '<div class="under-13-field">',
  );
  $form['parent_email'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Parent or Guardian\'s Email'),
    ),
    '#suffix' => '</div>',
    '#size' => 20,
  );

  $form['pass'] = array(
    '#type' => 'password_confirm',
    '#required' => TRUE,
    '#attributes' => array(
      'placeholder' => t('Create a Password'),
    ),
    '#maxlength' => 64,
    '#size' => 15,
  );
  if (module_exists('captcha')) {
    $form['captcha'] = array(
      '#title' => t('Captcha'),
      '#type' => 'captcha',
    );
  }

  $form['signup_title'] = array(
    '#type' => 'item',
    '#title' => t('Sign Up for Updates'),
    '#description' => t('In order to be a member, you have to be 25 and under.  However, this doesn\'t mean you can\'t stay up to date on our latests somethings.'),
    '#prefix' => '<div class="over-25-field">',
    '#suffix' => '</div>',
  );
  $form['signup'] = array(
    '#type' => 'checkbox',
    '#description' => t('Yes! I\'d love to receive the hilarious and informative weekly updates.'),
    '#prefix' => '<div class="over-25-field">',
    '#suffix' => '</div>',
  );
  $form['final_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * The form for the 'Become a Member' block.
 */
function dosomething_login_register_block($form, &$form_state) {
  $form['#attached'] = array(
    'js' => array(
      drupal_get_path('module', 'dosomething_login') . '/js/jquery-validation-1.9.0/jquery.validate.min.js',
      drupal_get_path('module', 'dosomething_login') . '/js/dosomething-login-member-lightbox.js',
    ),
    'library' => array(array('system', 'ui.dialog')),
  );
  $query = drupal_get_destination();
  $query['destination'] = $query['destination'] == 'user/registration' ? 'front' : $query['destination'];
  $form['#action'] = url($_GET['q'], array('query' => drupal_get_destination()));
  $form['#action'] = url('user/registration', array('query' => $query));
  $form['connect']['#markup'] = '<div class="connect-thru-facebook">' . l('Connect thru Facebook', 'fbconnect/register/create') . '</div>';
  $form['or']['#markup'] = '<div class="separator split">' . t('or') . '</div>';
  $form['name'] = array(
    'first_name' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('First Name'),
      ),
      '#size' => 9,
    ),
    'last_name' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('Last Name'),
      ),
      '#size' => 9,
    ),
  );
  $form['cell_or_email'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Cell Number or E-mail'),
    ),
    '#size' => 20,
  );
  $form['birthday'] = array(
    'over_13' => array('#markup' => '<div class="age-question">' . t('Over 13?') . '</div>'),
    'month' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('mm'),
      ),
      '#size' => 2,
      '#maxlength' => 2,
    ),
    'day' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('dd'),
      ),
      '#size' => 2,
      '#maxlength' => 2,
    ),
    'year' => array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('yyyy'),
      ),
      '#size' => 4,
      '#maxlength' => 4,
    ),
  );
  $form['first_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#attributes' => array('class' => array('submit')),
  );
  $form['why'] = array(
    '#theme' => 'link',
    '#path' => '',
    '#text' => t('Why become a member?'),
    '#options' => array(
      'attributes' => array('class' => array('why')),
      'html' => FALSE,
    ),
    '#prefix' => '<hr class="top"/><h3 class="why-member">',
    '#suffix' => '</h3><hr class="bottom"/>',
  );
  $form['lightbox'] = array(
    '#markup' => theme('dosomething_login_member_lightbox'),
    '#prefix' => '<div id="member-dialog">',
    '#suffix' => '</div>',
  );
  $form['already']['#markup'] = '<h3 class="already-member">' . t('Already a member?') . '</h3>';
  $form['logins'] = array(
    'facebook_login' => array('#markup' => l(
      '<span class="fb-icon">log in</span>',
      'fbconnect/login',
      array(
        'class' => 'login facebook-login ds-button',
        'html' => TRUE,
      )
    )
    ),
    'login' => array(
      '#theme' => 'link',
      '#path' => 'user/login',
      '#text' => t('log in'),
      '#options' => array(
        'attributes' => array('class' => array('login ds-login ds-button')),
        'html' => FALSE,
      ),
    ),
  );
  return $form;
}

/**
 * Validate the user registration form.
 */
function dosomething_login_register_block_validate($form, &$form_state) {
  $values = $form_state['values'];
  $form_state['values']['birthdate'] = mktime(0, 0, 0, $values['month'], $values['day'], $values['year']);
  if (!is_numeric($values['month']) || $values['month'] > 12) {
    form_set_error('month', t('Please provide a valid numeric month for your birthday.'));
    $invalid_birthday = TRUE;
  }
  if (!is_numeric($values['day']) || $values['month'] > 31) {
    form_set_error('day', t('Please provide a valid day for your birthday.'));
    $invalid_birthday = TRUE;
  }
  if (!is_numeric($values['year']) || strlen($values['year']) != 4) {
    form_set_error('year', t('Please provide the 4-digit year you were born.'));
    $invalid_birthday = TRUE;
  }
  if (!isset($invalid_birthday)) {
    if (!dosomething_login_person_is_over_age($form_state['values']['birthdate'], 13)) {
      if (!isset($form_state['values']['parent_email']) || !valid_email_address($form_state['values']['parent_email'])) {
        form_set_error('parent_email', t('Please provide a valid parental email address.'));
      }
    }
    else if (dosomething_login_person_is_over_age($form_state['values']['birthdate'], 25)) {
      // Don't throw required field errors for captcha and password.
      // We could add errors back if needed.
      form_clear_error();
      $messages = drupal_get_messages('error');
      if (count($messages['error'])) {
        foreach ($messages['error'] as $message) {
          if (!preg_match('/field is required.$/', $message)) {
            drupal_set_message($message, 'error');
          }
        }
      }
    }
  }

  if (!$values['first_name']) {
    form_set_error('first_name', t('Please provide your first name.'));
  }
  if (!$values['last_name']) {
    form_set_error('last_name', t('Please provide your last name.'));
  }
  // Validate cell number or e-mail address
  if (valid_email_address($values['cell_or_email'])) {
    if (db_select('users')->fields('users', array('uid'))->condition('mail', db_like($values['cell_or_email']), 'LIKE')->range(0, 1)->execute()->fetchField()) {
      form_set_error('cell_or_email', t('The e-mail address %email is already registered. <a href="@password">Have you forgotten your password?</a>', array('%email' => $values['cell_or_email'], '@password' => url('user/password'))));
    }
    $form_state['values']['mail'] = $values['cell_or_email'];
  }
  else if (($number = preg_replace('[^0-9]', '', $values['cell_or_email'])) && strlen($number) >= 10) {
    if (db_select('field_data_field_user_mobile')->fields('field_data_field_user_mobile', array('entity_id'))->condition('field_user_mobile_value', db_like($number), 'LIKE')->range(0, 1)->execute()->fetchField()) {
      form_set_error('cell_or_email', t('The phone number %phone is already registered. <a href="@password">Have you forgotten your password?</a>', array('%phone' => $values['cell_or_email'], '@password' => url('user/password'))));
    }
    else if (db_select('users')->fields('users', array('uid'))->condition('mail', db_like($number . '@mobile.com'), 'LIKE')->range(0, 1)->execute()->fetchField()) {
      form_set_error('cell_or_email', t('The phone number %phone is already registered. <a href="@password">Have you forgotten your password?</a>', array('%phone' => $values['cell_or_email'], '@password' => url('user/password'))));
    }
    $form_state['values']['phone'] = $number;
    $form_state['values']['mail'] = $number . '@mobile.com';;
  }
  else {
    form_set_error('cell_or_email', t('Please provide a valid email address or phone number'));
  }
}

/**
 * Submit the user registration form.
 */
function dosomething_login_register_block_submit($form, &$form_state) {
  $values = $form_state['values'];
  $birthdate = $values['birthdate'];
  $name = preg_replace('/[^A-Za-z.]+/', '', $values['first_name']) . ' ' . preg_replace('/[^A-Za-z.]+/', '', $values['last_name']);
  $form_state['values']['name'] = dosomething_login_unique_name($name);
  $form_state['values']['init'] = $name;
  if (empty($form_state['values']['pass'])) {
    $form_state['values']['pass'] = user_password();
  }
  // Remove unneeded values.
  form_state_values_clean($form_state);

  $account = drupal_anonymous_user();
  $edit = array_intersect_key((array) $account, $form_state['values']);
  $edit['pass'] = $form_state['values']['pass'];
  entity_form_submit_build_entity('user', $account, $form, $form_state);

  // Determine the user's role by their age.
  if (dosomething_login_person_is_over_age($birthdate, 25)) {
    $role_name = 'old person';
    drupal_set_message(t('You have been signed up for our weekly updates'));
    $account->status = 0;
  }
  else if (!dosomething_login_person_is_over_age($birthdate, 13)) {
    $role_name = 'pending member';
    $account->status = 1;
  }
  else {
    $role_name = 'member';
    $account->status = 1;
  }
  $role = user_role_load_by_name($role_name);
  $account->roles[$role->rid] = $role->name;
  $account = user_save($account, $edit);

  // Terminate if an error occurred during user_save().
  if (!$account) {
    drupal_set_message(t("Error saving user account."), 'error');
    $form_state['redirect'] = '';
    return;
  }
  // Save profile data.
  $profile = new stdClass();
  $profile->type = 'main';
  $profile->uid = $account->uid;
  drupal_write_record('profile', $profile);
  $profile->field_user_first_name[LANGUAGE_NONE][0]['value'] = $values['first_name'];
  $profile->field_user_last_name[LANGUAGE_NONE][0]['value'] = $values['last_name'];
  $birthday = new DateObject($values['birthdate']);
  $time = $birthday->format(DATE_FORMAT_DATETIME);
  $profile->field_user_birthday[LANGUAGE_NONE][0]['value'] = $time;
  $profile->field_user_is_over13[LANGUAGE_NONE][0]['value'] = (int) dosomething_login_person_is_over_age($values['birthdate'], 13);
  if ($values['signup'] || $role_name == 'old person') {
    $profile->field_user_newsletter_optin[LANGUAGE_NONE][0]['value'] = 1;
  }
  if (isset($values['phone'])) {
    $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] = $values['phone'];
  }
  field_attach_insert('profile2', $profile);
  $form_state['uid'] = $account->uid;
  if (isset($account->mail) && $account->status) {
    _user_mail_notify('register_no_approval_required', $account);
    drupal_set_message(t('Please check your email to verify your account.'));
  }
  else {
    // TOOD: verify cell number via SMS.
  }

  if (!dosomething_login_person_is_over_age($values['birthdate'], 13)) {
    if (isset($values['parent_email'])) {
      global $language;
      $params = array('account' => $account);
      drupal_mail('dosomething_login', 'dosomething-parent-email', $values['parent_email'], $language, $params);
      drupal_set_message(t('An email has been sent to %email for permission.', array('%email' => $values['parent_email'])));
    }
  }
}

/**
 * Generate a unique username.
 */
function dosomething_login_unique_name($name, $i = '') {
  if (db_select('users')->fields('users', array('uid'))->condition('name', db_like($name . $i), 'LIKE')->range(0, 1)->execute()->fetchField()) {
    if ($i === '') {
      $i = 0;
    }
    else {
      $i++;
    }
    return dosomething_login_unique_name($name, $i);
  }
  else {
    return $name . $i;
  }
}

function dosomething_login_mobile_signup_access() {
  $valid = sms_mobile_commons_incoming_check();

  //TODO: REMOVE ME BEFORE PRODUCTION!!!
  //For testing allow ip of zivtech office and local dev machines
  $ip = ip_address();
  if ($ip == '192.168.56.1' || $ip == '173.161.182.250') {
    $valid = TRUE;
  }
  if (!$valid) {
    //We've got someone trying to create users on the mobile page. That's bad.
    watchdog('dosomething_login',
      'Someone is trying to mobile signup from ip address: ' . $ip
      . " This is suspicious.", $variables = array(), $severity = WATCHDOG_NOTICE, $link = NULL);
  }
  return $valid;
}

function dosomething_login_mobile_signup() {
  //TODO REMOVE ME. I AM FOR TESTING ONLY.
  $ip = ip_address();
  watchdog('dosomething_login', $ip . " " . $_SERVER['REQUEST_URI'], $variables = array(), $severity = WATCHDOG_NOTICE, $link = NULL);

  return 'THIS IS A TEST';
}

/**
 * Member dashboard block for logged in users.
 */
function dosomething_login_member_block() {
  global $user;
  drupal_add_js(drupal_get_path('module', 'dosomething_login') . '/js/show-member-items.js');
  $output = '<div class="dosomething-login-user-name">' . '<h2>' . check_plain($user->name) . '</h2><span class="user-role">( ' . dosomething_login_user_role() . ' )</span></div>';
  $output .= '<div class="dosomething-login-profile">' . dosomething_login_profile_completion() . '</div>';
  $output .= dosomething_login_my_somethings();
  $output .= dosomething_login_notifications();
  //$output .= l('Go to profile >>', 'user', array('attributes' => array('class' => array('dosomething-login-goto-profile'))));
  return $output;
}

function dosomething_login_user_role($account = NULL) {
  if (!isset($account)) {
    global $user;
    $account = $user;
  }
  $roles = $account->roles;
  $member = user_role_load_by_name('member');
  if (isset($roles[$member->rid])) {
    return t('member');
  }
  $active_member = user_role_load_by_name('active member');
  if (isset($roles[$active_member->rid])) {
    return 'active';
  }
  return t('inactive');
}

function dosomething_login_profile_completion() {
  global $user;
  $ratio = dosomething_login_profile_percentage();
  $output = '<div class="profile-header">' . t('My profile: %percent', array('%percent' => number_format($ratio, 0) . '%')) .  l('Complete >>', 'user/' . $user->uid . '/edit/main') . '</div>';
  $output .= '<div class="dosomething-login-percentage"><div class="ratio" data-ratio="' . $ratio . '"><div class="inner" style="width: ' . $ratio . '%">' . $ratio . '</div></div></div>';
  return $output;
}

function dosomething_login_my_somethings() {
  $output = '<h2 class="my-somethings"><div class="inner">' . t('My Somethings') . '</div></h2>';
  $items[] = array('data' => t('My Current Somethings'), 'children' => dosomething_login_my_current_somethings());
  $items[] = array('data' => t('My Opportunities'), 'children' => dosomething_login_my_opportunities());
  $output .= theme('item_list', array('items' => $items, 'attributes' => array('class' => 'my-somethings')));
  return $output;
}

function dosomething_login_notifications() {
  $output = '<h2 class="notifications"><div class="inner">' . t('Notifications') . '</div></h2>';
  // TODO: replace dummy content
  $items[] = 'Fox Lane book drive | ' . l('Report Back', '<front>');
  $items[] = 'Fox Lane book drive | ' . l('Report Back', '<front>');
  $output .= theme('item_list', array('items' => $items, 'attributes' => array('class' => 'notifications')));
  return $output;
}

function dosomething_login_profile_percentage() {
  global $user;
  $profile = profile2_load_by_user($user);
  $total = 0;
  $complete = 0;
  if (isset($profile['main'])) {
    foreach ($profile['main'] as $field_name => $values) {
      if (substr($field_name, 0, 5) == 'field') {
        $total++;
        if (count($values)) {
          $complete++;
        }
      }
    }
  }
  if ($total) {
    return (($complete / $total) * 100);
  }
  return 0;
}

function dosomething_login_my_current_somethings() {
  // TODO: replace dummy content
  $items[] = 'Fox Lane book drive | ' . l('Report Back', '<front>');
  $items[] = 'Fox Lane book drive | ' . l('Report Back', '<front>');
  return $items;
}

function dosomething_login_my_opportunities() {
  // TODO: replace dummy content
  $items[] = 'Fox Lane book drive | ' . l('Report Back', '<front>');
  $items[] = 'Fox Lane book drive | ' . l('Report Back', '<front>');
  return $items;
}

/**
 * Add necessary registration items to fbconnect registration form.
 */
function dosomething_login_form_fbconnect_register_page_alter(&$form, $form_state) {
  if (isset($form['account']['mail']['#value'])) {
    $data = fbconnect_get_user_info(array('first_name', 'last_name'));
    $form['dosomething_name'] = array(
      'first_name' => array(
        '#type' => 'textfield',
        '#attributes' => array(
          'placeholder' => t('First Name'),
        ),
        '#default_value' => $data['first_name'],
        '#size' => 9,
      ),
      'last_name' => array(
        '#type' => 'textfield',
        '#attributes' => array(
          'placeholder' => t('Last Name'),
        ),
        '#default_value' => $data['last_name'],
        '#size' => 9,
      ),
    );
    $form['cell'] = array(
      '#type' => 'textfield',
      '#attributes' => array(
        'placeholder' => t('Cell Number'),
      ),
      '#size' => 20,
    );
    $form['birthday'] = array(
      'over_13' => array('#markup' => '<div class="age-question">' . t('Over 13?') . '</div>'),
      'month' => array(
        '#type' => 'textfield',
        '#attributes' => array(
          'placeholder' => t('mm'),
        ),
        '#size' => 2,
        '#maxlength' => 2,
      ),
      'day' => array(
        '#type' => 'textfield',
        '#attributes' => array(
          'placeholder' => t('dd'),
        ),
        '#size' => 2,
        '#maxlength' => 2,
      ),
      'year' => array(
        '#type' => 'textfield',
        '#attributes' => array(
          'placeholder' => t('yyyy'),
        ),
        '#size' => 4,
        '#maxlength' => 4,
      ),
    );
    $form['#validate'][] = 'dosomething_login_fbconnect_register_validate';
    $form['#submit'][] = 'dosomething_login_fbconnect_register_submit';
  }
}

function dosomething_login_fbconnect_register_submit($form, &$form_state) {
  $values = $form_state['values'];
  $account = $form_state['user'];
  // Save profile data.
  $profile = new stdClass();
  $profile->type = 'main';
  $profile->uid = $account->uid;
  drupal_write_record('profile', $profile);
  $profile->field_user_first_name[LANGUAGE_NONE][0]['value'] = $values['first_name'];
  $profile->field_user_last_name[LANGUAGE_NONE][0]['value'] = $values['last_name'];
  $birthday = new DateObject($values['birthdate']);

  // Determine the user's role by their age.
  $member_role = user_role_load_by_name('member');
  if (dosomething_login_person_is_over_age($values['birthdate'], 25)) {
    $role_name = 'old person';
    drupal_set_message(t('Thank you for registering. Unfortunately, we do not allow accounts for people over 26.'));
    $account->status = 0;
    unset($account->roles[$member_role->rid]);
  }
  else if (!dosomething_login_person_is_over_age($values['birthdate'], 13)) {
    $role_name = 'pending member';
    unset($account->roles[$member_role->rid]);
  }
  else {
    $role_name = 'member';
  }
  $role = user_role_load_by_name($role_name);
  $account->roles[$role->rid] = $role->name;
  $account = user_save($account);

  $time = $birthday->format(DATE_FORMAT_DATETIME);
  $profile->field_user_birthday[LANGUAGE_NONE][0]['value'] = $time;
  $profile->field_user_is_over13[LANGUAGE_NONE][0]['value'] = (int) dosomething_login_person_is_over_age($values['birthdate'], 13);
  if (isset($values['phone'])) {
    $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] = $values['phone'];
  }
  field_attach_insert('profile2', $profile);
}

function dosomething_login_fbconnect_register_validate($form, &$form_state) {
  $values = $form_state['values'];
  if (!$values['first_name']) {
    form_set_error('first_name', t('Please provide your first name.'));
  }
  if (!$values['last_name']) {
    form_set_error('last_name', t('Please provide your last name.'));
  }
  // Validate cell number
  if (($number = preg_replace('[^0-9]', '', $values['cell'])) && strlen($number) >= 10) {
    if (db_select('field_data_field_user_mobile')->fields('field_data_field_user_mobile', array('entity_id'))->condition('field_user_mobile_value', db_like($number), 'LIKE')->range(0, 1)->execute()->fetchField()) {
      form_set_error('cell_or_email', t('The phone number %phone is already registered. <a href="@password">Have you forgotten your password?</a>', array('%phone' => $values['cell_or_email'], '@password' => url('user/password'))));
    }
    $form_state['values']['phone'] = $number;
  }
  if (!is_numeric($values['month']) || $values['month'] > 12) {
    form_set_error('month', t('Please provide a valid numeric month for your birthday.'));
    $invalid_birthday = TRUE;
  }
  if (!is_numeric($values['day']) || $values['month'] > 31) {
    form_set_error('day', t('Please provide a valid day for your birthday.'));
    $invalid_birthday = TRUE;
  }
  if (!is_numeric($values['year']) || strlen($values['year']) != 4) {
    form_set_error('year', t('Please provide the 4-digit year you were born.'));
    $invalid_birthday = TRUE;
  }
  if (!isset($invalid_birthday)) {
    $birthday = mktime(0, 0, 0, $values['month'], $values['day'], $values['year']);
    $form_state['values']['birthdate'] = $birthday;
    if (dosomething_login_person_is_over_age($birthday, 13)) {
      form_set_error('year', t('Members must be at least 13 years old.'));
    }
  }
}

/**
 * Determine if a drupal user is over 13 years old.
 *
 * @param $uid
 *  (int) numeric id of drupal user.
 * @return @boolean
 */
function dosomething_login_drupal_user_is_over_age($uid, $age = 13) {
  $account = user_load($uid);
  $profile = profile2_load_by_user($account, 'main');
  if (is_object($profile)) {
    $birthday = field_get_items('profile2', $profile, 'field_user_birthday'); 
    if (isset($birthday[0]['value'])) {
      // this is only a a time (no time) so timezone is not important.
      $timestamp = strtotime($birthday[0]['value']);
      return dosomething_login_person_is_over_age($timestamp, $age);
    }
  }
  return FALSE;
}

/**
 * Check if a user is over 13.
 *
 * @param $birthday
 *  (int) timestamp of birthday.
 * @return @boolean
 */
function dosomething_login_person_is_over_age($birthday, $age = 13) {
  return $birthday < strtotime("-$age year") ? TRUE : FALSE;
}

/**
 * Mark a user as being over 13.
 *  They don't need parental permission at this point.
 */
function dosomething_login_mark_user_account_over_13($uid) {
  // TODO: What else needs to be done to graduate the user to being over 13?
  $account = user_load($uid);
  $profile = profile2_load_by_user($account, 'main');
  if (is_object($profile)) {
    $birthday = field_get_items('profile2', $profile, 'field_user_birthday'); 
    $profile->field_user_is_over13[LANGUAGE_NONE][0]['value'] = 1;
    profile2_save($profile);
  }
}

/**
 * Get a user's full name from their main profile.
 */
function dosomething_login_get_user_full_name($account) {
  $full_name = '';
  $names = array();
  $profile = profile2_load_by_user($account, 'main');
  if (is_object($profile)) {
    foreach (array('field_user_first_name', 'field_user_last_name') as $field) {
      $stored_names = field_get_items('profile2', $profile, $field); 
      if (isset($stored_names[0]['safe_value'])) {
        $names[] = $stored_names[0]['safe_value'];
      }
    }
    $full_name = implode(' ', $names);
  }
  return $full_name;
}

/**
 * Determine if user has parentel consent to use this site.
 *  If they are over 13, then they don't need it.
 */
function dosomething_login_user_has_parental_consent($uid) {
  if (dosomething_login_drupal_user_is_over_age($uid)) {
    return TRUE;
  }
  $account = user_load($uid);
  if (!in_array('pending member', $account->roles)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Set a message indicating that s user cannot perform an action
 *  until the have been given consent by a parent.
 */
function dosomething_login_set_parental_consent_message() {
  // TODO: Some link to ask for parental consent
  drupal_set_message(t('Before you can perform this action, you must have parental consent. You can send a request to your parent or legal guardian <a href="@link"> here</a>.', array('@link' => 'dosomething/under-13/parent-consent-email')));
}

/**
 * Determine access to parental consent email request form.
 */
function dosomething_parent_consent_email_access() {
  global $user;
  return !dosomething_login_user_has_parental_consent($user->uid);
}

/**
 * Form for a person under 13 to request their parent's permission
 *  to use the site.
 */
function dosomething_login_parent_permission_email_form($form, &$form_state, $uid = NULL) {
  if (is_null($uid)) {
    global $user;
    $uid = $user->uid;
  }
  $form['parent_email'] = array(
    '#title' => t('Parent Email Address'),
    '#type' => 'textfield',
    '#size' => 20,
  );
  $form['uid'] = array(
    '#type' => 'value',
    '#value' => $uid,
  );
  $form['submit_email'] = array(
    '#type' => 'submit',
    '#value' => t('Send Email'),
  );
  return $form;
}

/**
 * Validation callback for parent permission email form.
 */
function dosomething_login_parent_permission_email_form_validate($form, &$form_state) {
  $email = $form_state['values']['parent_email'];
  if (!valid_email_address($email)) {
    form_set_error('parent_email', t('you must provide a valid email address'));
  }
}

/**
 * Submission callback for parent permission email form.
 */
function dosomething_login_parent_permission_email_form_submit($form, &$form_state) {
  global $language;
  $email = $form_state['values']['parent_email'];
  $account = user_load($form_state['values']['uid']);
  $params = array('account' => $account);

  drupal_mail('dosomething_login', 'dosomething-parent-email', $email, $language, $params);
  // TODO: This message may not be necessary.
  drupal_set_message(t('An email has been sent to %email.', array('%email' => $email)));
}

/**
 * Generates a unique URL for a parent to give permission to their
 *  under 13 year old child.
 *
 * @param object $account
 *   An object containing the user account.
 *
 * @return
 *   A unique URL that provides a one-time link for the user.
 */
function dosomething_login_one_time_parent_permission_link($account) {
  $timestamp = REQUEST_TIME;
  return url("dosomething/under-13/permission/$account->uid/$timestamp/" . user_pass_rehash($account->pass, $timestamp, $account->created), array('absolute' => TRUE));
}

/**
 * Page callback for parental consent link.
 *  This is used for users under 13 who need consent to be members.
 */
function dosomething_login_parent_permission_page($form, &$form_state, $uid, $timestamp, $hash, $action = NULL) {
  // TODO: This expires after 6 months (maybe sooner).
  global $language;
  $timeout = strtotime('-6 months');
  $current = REQUEST_TIME;
  // Some redundant checks for extra security ?
  $users = user_load_multiple(array($uid), array('status' => '1'));
  if ($timestamp <= $current && $account = reset($users)) {
    // No time out for first time login.
    if ($timestamp < $timeout) {
      drupal_set_message(t('You have tried a parental consent link that has expired.'));
      drupal_goto();
    }
    elseif ($account->uid && $timestamp <= $current && $hash == user_pass_rehash($account->pass, $timestamp, $account->created)) {
      if (dosomething_login_user_has_parental_consent($uid)) {
        drupal_set_message(t('%user_name is either over 13 or has already received parental consent.', array('%user_name' => $account->name)));
        drupal_goto();
      }
      if ($action == 'submit') {
        if (isset($form_state['input']['op'])) {
          // Determine whether the parent is granting or denying membership.
          switch ($form_state['input']['op']) {
            case t('Yes'):
              watchdog('dosomething', 'User %name was given parental permission to be a member.', array('%name' => $account->name));
              drupal_set_message(t('You have just allowed %user_name to be a member of this site.  An email has been sent.', array('%user_name' => $account->name)));
              drupal_mail('dosomething_login', 'dosomething-parent-permission-granted-email', $account->mail, $language, array('account' => $account));
              dosomething_login_grant_user_parental_permission($account);
              break;

            case t('No'):
              watchdog('dosomething', 'User %name was NOT given parental permission to be a member.', array('%name' => $account->name));
              drupal_set_message(t('%user_name has been denied parental consent to be a member of this site.  An email has been sent.', array('%user_name' => $account->name)));
              drupal_mail('dosomething_login', 'dosomething-parent-permission-denied-email', $account->mail, $language, array('account' => $account));
              dosomething_login_deny_user_parental_permission($account);
              break;

            default:
              drupal_set_message(t('You provided an invalid response.'), 'warning');
              drupal_goto("dosomething/under-13/permission/$uid/$timestamp/$hash");
              break;
          }
        }
        else {
          drupal_set_message(t('You provided an invalid response.'), 'warning');
        }
        drupal_goto();
      }
      // TODO: else if user already has permission by virtue of being 13 or older.
      else {
        $form['message'] = array('#markup' => t('<p>Will you allow %user_name to be a member of this site?</p>',  array('%user_name' => $account->name)));
        $form['actions'] = array('#type' => 'actions');
        $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Yes'));
        $form['actions']['cancel'] = array('#type' => 'submit', '#value' => t('No'));
        $form['#action'] = url("dosomething/under-13/permission/$uid/$timestamp/$hash/submit");
        return $form;
      }
    } 
  }
  else {
    drupal_set_message(t('You have tried to use a parental permission link that has either been used or is not valid.'));
    drupal_goto('');
  }
}

/**
 * Give a user under 13 parental permission.
 */
function dosomething_login_grant_user_parental_permission($account) {
  $member = user_role_load_by_name('member');
  $pending_member = user_role_load_by_name('pending member');
  // Only set the roles if they are a pending member.
  if (isset($account->roles[$pending_member->rid])) {
    $account->roles[$member->rid] = $member->name;
    unset($account->roles[$pending_member->rid]);
    $account = user_save($account);
  }
}

/**
 * Give a user under 13 parental permission.
 */
function dosomething_login_deny_user_parental_permission($account) {
  // TODO: Should we do anything to deny a user access?
  // Delete their account, or deactivate it?
}

/**
 * Update users who have become 13 or older.
 */
function dosomething_login_update_accounts_under_13($limit = 10) {
  $profiles = dosomething_login_get_accounts_under_13($limit);
  if (isset($profiles['profile2']) && count($profiles['profile2'])) {
    foreach ($profiles['profile2'] as $profile_data) {
      $profile = profile2_load($profile_data->pid);
      $birthday = field_get_items('profile2', $profile, 'field_user_birthday');
      if (isset($birthday[0]['value'])) {
        if (dosomething_login_person_is_over_age(strtotime($birthday[0]['value']), 13)) {
          $profile->field_user_is_over13[LANGUAGE_NONE][0]['value'] = 1;
          profile2_save($profile);
          $account = user_load($profile->uid);
          dosomething_login_grant_user_parental_permission($account);
        }
      }
    }
  }
}

/**
 * Get a list of accounts who are under 13
 */
function dosomething_login_get_accounts_under_13($limit = 10) {
  //Grab users in order of their birthdays
  // depending on whether they're marked under 13.
  $query = new EntityFieldQuery;

  try {
    $result = $query
      ->entityCondition('entity_type', 'profile2')
      ->propertyCondition('type', 'main')
      ->fieldCondition('field_user_is_over13', 'value', 0, '=')
      ->fieldOrderBy('field_user_birthday', 'value', 'ASC')
      ->range(0, $limit)
      ->execute();
  } catch (Exception $e) {
    // TODO: Some watchdog notice.
    return 0;
  }
  return $result;
}

/**
 * Delete old accounts of users who are under 13 and
 *  haven't received permission from there parents.
 */
function dosomething_login_clear_old_accounts($limit = 10) {
  $accounts = dosomething_login_get_old_accounts($limit);
  if (count($accounts)) {
    foreach ($accounts as $uid) {
      if ($uid != 1) {
        user_delete($uid);
      }
    }
  }
}

/**
 * Get the count of unassigned notifications.
 */
function dosomething_login_get_old_accounts($limit = 10) {
  $records = array();
  $role = user_role_load_by_name('pending member');
  try {
    $query = db_select('users', 'u');
    $query->innerJoin('users_roles', 'r', 'r.uid = u.uid');
    $result = $query->fields('u', array('uid'))
      ->condition('r.rid', $role->rid, '=')
      ->condition('u.status', 1, '=')
      ->condition('u.created', strtotime('-6 months'), '<')
      ->orderBy('u.created', 'ASC')
      ->range(0, $limit)
      ->execute();

  } catch (Exception $e) {
    // TODO: Some watchdog notice.
    return array();
  }
  while($record = $result->fetchAssoc()) {
    $records[] = $record;
  }
  return $records;
}

