<?php
/**
 * @file
 * Code for the dosomething_feedback feature.
 */

include_once('dosomething_feedback.features.inc');

/**
 * Default the name field to use the user name.
 */
function dosomething_feedback_form_feedback_form_alter(&$form, $form_state) {
  global $user;
  if ($user->uid) {
    $form['field_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $user->name;
  }
}

/**
 * Implements hook_unfuddle_feedback_fields_alter().
 */
function dosomething_feedback_unfuddle_feedback_fields_alter(&$fields, $entry) {
  if (isset($entry->field_priority[LANGUAGE_NONE][0]['value'])) {
    switch($entry->field_priority[LANGUAGE_NONE][0]['value']) {
      case 'Critical':
        $fields['priority'] = 5;
        break;
      case 'High':
        $fields['priority'] = 4;
        break;
      case 'Medium':
        $fields['priority'] = 3;
        break;
      case 'Low':
        $fields['priority'] = 2;
        break;
      case 'Enhancement':
        $fields['priority'] = 1;
        break;
    }
  }
  $fields['description-format'] = 'plain';
  $fields['assignee-id'] = 48329;
  $fields['milestone-id'] = 357;
}

/**
 * Implements hook_unfuddle_feedback_subject_alter().
 */
function dosomething_feedback_unfuddle_feedback_subject_alter(&$subject, $entry) {
  if (isset($entry->field_summary[LANGUAGE_NONE][0]['value'])) {
    $subject = check_plain($entry->field_summary[LANGUAGE_NONE][0]['value']);
  }
  else {
    $subject = $entry->location;
    $subject .= ' (' . check_plain($entry->field_name[LANGUAGE_NONE][0]['value']) . ')';
  } 
}

/**
 * Implements hook_feedback_insert().
 */
function dosomething_feedback_feedback_insert($entry) {
  global $user;
  include_once(drupal_get_path('module', 'feedback') . '/feedback.admin.inc');
  $description = drupal_html_to_text(drupal_render(feedback_view($entry)));
  $params['body'] = $description;
  $emails = array('benji@zivtech.com', 'kfong@dosomething.org', 'jody@zivtech.com');
  foreach ($emails as $to) {
    drupal_mail('dosomething_feedback', 'mail', $to, language_default(), $params);
  }
}

/**
 * Implements hook_mail().
 */
function dosomething_feedback_mail($key, &$message, $params) {
  $message['subject'] = 'New Feedback from DoSomething';
  $message['body'][] = $params['body'];
}
