<?php

$plugin = array(
  'title' => t('One Two One Two'),
  'category' => t('Dosomething'),
  'icon' => 'one_two_one_two.png',
  'theme' => 'dosomething_panels_one_two_one_two',
  'css' => 'one_two_one_two.css',
  'regions' => array(
    'top' => t('Top'),
    'row2-left' => t('Row 2 Left'),
    'row2-right' => t('Row 2 Right'),
    'row3' => t('Row 3'),
    'bottom-left' => t('Bottom Left'),
    'bottom-right' => t('Bottom Right'),
  ),
);
