<?php

$plugin = array(
  'title' => t('Two Three'),
  'category' => t('Dosomething'),
  'icon' => 'two_three.png',
  'theme' => 'dosomething_panels_two_three',
  'css' => 'two_three.css',
  'regions' => array(
    'top-left' => t('Top - Left'),
    'top-right' => t('Top - Right'),
    'bottom-left' => t('Bottom - Left'),
    'bottom-center' => t('Bottom - Center'),
    'bottom-right' => t('Bottom - Right'),
  ),
);
