<?php

/**
 * @file
 * Basic module file to handle redirect of picsforpets urls
 */

/**
 * Implements hook_init().
 */
function dosomething_picsforpets_redirect_init() {
  // Just bail out quickly if we're not on a pics for pets page.
  if (!(strpos(drupal_get_path_alias(request_uri()), '/pics-for-pets') === 0)) {
    return;
  }
  drupal_add_js(drupal_get_path('module', 'dosomething_picsforpets_redirect') . '/js/pfpredirect.js');
}
