<?php

/**
 * @file
 * Stathat module.
 */

/**
 * Implements hook_libraries_info().
 */
function stathat_libraries_info() {
  $libraries['stathat'] = array(
    'name' => 'StatHat',
    'vendor url' => 'https://www.stathat.com',
    'download url' => 'https://www.stathat.com/downloads/stathat.php',
    'version' => '1.0',
    'files' => array(
      'php' => array('stathat.php'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_permission().
 */
function stathat_permission() {
  return array(
    'administer stathat' => array(
      'title' => t('Administer StatHat'),
      'description' => t('Perform administration tasks for StatHat.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stathat_menu() {
  $items['admin/config/system/stathat'] = array(
    'title' => 'StatHat',
    'description' => 'Configure StatHat ezkey and settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stathat_admin_settings_form'),
    'access arguments' => array('administer stathat'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'stathat.admin.inc',
  ); 
  return $items;
}
