<?php

/**
 * @file
 * Stathat module.
 */

/*
 * Implements hook_libraries_info().
 */
function stathat_libraries_info() {
  $libraries['stathat'] = array(
    'name' => 'StatHat',
    'vendor url' => 'https://www.stathat.com',
    'download url' => 'https://www.stathat.com/downloads/stathat.php',
    'version' => '1.0',
    'files' => array(
      'php' => array('stathat.php'),
    ),
  );
  return $libraries;
}

/*
 * Implements hook_permission().
 */
function stathat_permission() {
  return array(
    'administer stathat' => array(
      'title' => t('Administer StatHat'),
      'description' => t('Perform administration tasks for StatHat.'),
    ),
  );
}
