<?php

function dosomething_contact_picker_menu() {
  $items['invite-by-email-scraper/%'] = array(
    'page callback' => 'dosomething_contact_scraper_invite',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['contacts-scraper/%'] = array(
    'page callback' => 'dosomething_contact_scraper_land',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['contacts-scraper/%/done'] = array(
    'page callback' => 'dosomething_contact_scraper_land',
    'page arguments' => array(1, TRUE),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function dosomething_contact_picker_theme($existing, $type, $theme, $path) {
  return array(
    'contact_scraper_landing' => array(
      'path' => $path . '/templates',
      'variables' => array(
        'title' => NULL,
        'nid' => NULL,
        'email_text' => NULL
      ),
      'template' => 'contact-scraper-landing',
    ),
    'contact_scraper_done' => array(
      'path' => $path . '/templates',
      'variables' => array(
        'title' => NULL,
        'nid' => NULL
      ),
      'template' => 'contact-scraper-done',
    )
   );
 }


function dosomething_contact_scraper_land($nid, $done = FALSE) {
	if (empty($nid) || !intval($nid)) {
		exit;
	}

	$node = node_load($nid);
	if (!$done && intval($nid)) {
	  $a = user_load($node->uid);
	  $p = profile2_load_by_user($a, 'main');
	  $author = $p->field_user_first_name[LANGUAGE_NONE][0]['value'];
	  if (!trim($author)) {
	    $author = $a->name;
	  }

	  $e = theme('ds_petitions_invite', array(
		'title' => $node->title,
		'nid' => $node->nid,
	    'signatures' => number_format($node->field_petition_goal[LANGUAGE_NONE][0]['value']),
	    'url' => url(drupal_lookup_path('alias', 'node/' . $node->nid), array('absolute' => TRUE)),
	    'first_name' => $author
	  ));
	  $e = str_replace(array("\n", '"'), array('\r\n', '\"'), $e);

	  echo theme('contact_scraper_landing', array(
		'title' => $node->title,
		'nid' => $node->nid,
	    'email_text' => $e
	  ));
	}
	else if ($done) {
	  echo theme('contact_scraper_done', array(
		'title' => $node->title,
		'nid' => $node->nid
	  ));
	}
	exit;
}

function dosomething_contact_scraper_invite($nid) {
	if ($_POST['do'] == 'email') {
	  $node = node_load($nid);
  	  global $user;
  	  $p = profile2_load_by_user($user, 'main');
  	  if (isset($p->field_user_first_name[LANGUAGE_NONE][0]['value'])) {
  		$me = $p->field_user_first_name[LANGUAGE_NONE][0]['value'];
  	  }
  	  else {
  		$me = $user->name;
  	  }

  	  $node->link = url(drupal_lookup_path('alias', 'node/' . $node->nid), array('absolute' => TRUE));

	  $a = user_load($node->uid);
	  $p = profile2_load_by_user($a, 'main');
	  $author = $p->field_user_first_name[LANGUAGE_NONE][0]['value'];
	  if (!trim($author)) {
	    $author = $a->name;
	  }

	  global $language;
	  $params = array(
	    'title' => $node->title,
	    'signatures' => number_format($node->field_petition_goal[LANGUAGE_NONE][0]['value']),
	    'url' => $node->link,
	    'first_name' => $author,
	  );

	  foreach (explode(',', $_POST['real_emails']) AS $email) {
	    if (valid_email_address(trim($email))) {
	      drupal_mail('dosomething_petitions', 'petition_invite', trim($email), $language, $params);
	      dosomething_petitions_store_email($node->nid, $user->uid, $email);
	    }
	  }

	  if ($user->mail) {
	  	global $language;
		  $params = array(
		  	'name' => $me,
		  	'petition' => $node->title,
		  	'author' => $author
		  );

		  drupal_mail('dosomething_petitions', 'thanks_for_inviting', $user->mail, $language, $params);
	  }

	  drupal_set_message(t('Thanks, we have emailed them.'));
	  drupal_goto('contacts-scraper/' . $node->nid . '/done');
	}
}