<?php

/**
 * Class of constants to be used for sms_flow_game game_id's
 * Constants shouldn't be removed from this and repurposed for other SMS flows
 * unless you know what you're getting yourself into.
 */
class SmsFlowGameConstants {
  const WYR_GAME                = 2;
  const FINANCIAL_ED_TIPS       = 3;
  const PBJ_MARKETING_TIPS      = 4;
  const PBJ_DRIVE_TIPS          = 5;
  const PREGTEXT_WAIT_TIPS      = 6;
  const PREGTEXT_SAFE_TIPS      = 7;
  const PREGTEXT_PARENT_TIPS    = 8;
  const PREGTEXT_RIGHTS_TIPS    = 9;
  const THUMBWARS_IDEAS_TIPS    = 10;
  const THUMBWARS_FACTS_TIPS    = 11;
  const PUPPYTEXT_FAQ_TIPS      = 12;
  const PUPPYTEXT_DOG_TIPS      = 13;
  const OK_ART_TIPS             = 14;
  const CLIMATE_SAS_NINJA       = 15;
  const IHEARTDAD_BP_TIPS       = 16;
  const IHEARTDAD_HEALTH_TIPS   = 17;
  const IHEARTDAD_GUIDE         = 18;
  const HUNT_INSPIRE            = 19;
  const BDAYMAIL_TIPS           = 20;
}