<?php

/**
 *  Begins the most epic SMS flow ever.  But seriously, opts an Alpha into a Mobile Commons campaign.  Then opts in Betas into another Mobile Commons
 *  campaign.  Sends $variables (an array of custom variables, surprisingly) along with those opt-ins.  Apply this function in a form submit function.
 *  
 *  @param $alpha_number
 *    The phone number of the alpha who invited the betas.
 *  @param $alpha_optin
 *    A campaign number on mobile commons that the ALPHA will be opted in to.
 *  @param $beta_optin
 *    A campaign on mobile commons that the BETA will be opted into.
 *  @param $beta_numbers
 *    An array of the field keys that represent the phone numbers that the alpha invited through the form.
 *    ALTERNATELY: An array of valid phone numbers to opt in through the opt-in path.
 *  @param $form_values
 *    An array of form values from the submitted webform.
 *  @param $beta_variables
 *    An array of custom variables to send with the opt-in. Are only applied to the Beta profiles. These translate to {{variables}} on Mobile Commons.
 *  @param $beta_to_alpha_campaign
 *    A campaign that the beta (then Gamma, then whatever is after Gamma) should be opted into when they invite their friends.  Optional.
 *  @param $type_override (optional)
 *    Set a custom value to the 'type' column. Particularly useful for cases where there is no appropriate NID 
 *    or Drupal type for this invite. ex: the MLK day SMS game
 *
 *  Example (found in dosomething_clubs_preserve_shortform_email() in dosomething_clubs.module):
 *    sms_flow_start('610-368-3195', 128441, 128441, array('field_webform_mobile'), $form_state['values'], array(
 *      'first_name' => 'Mike',
 *      'club_name' => "Mike's cool DoSomething.org Club."
 *    ));
 *
 */

function sms_flow_start($alpha_number, $alpha_optin, $beta_optin, Array $beta_numbers, $form_values, Array $beta_variables, $beta_to_alpha_campaign = FALSE, $type_override = NULL) {

  $nid = 0;
  if (!empty($form_values['details']['nid'])) {
    $nid = $form_values['details']['nid'];
  }

  if (empty($type_override)) {
    $n = node_load($nid);
    $type = $n->type;
  }
  else {
    $type = $type_override;
  }

  $alpha_number = preg_replace('#[^0-9]#', '', $alpha_number);

  $valid_beta_numbers = array();
  foreach ($beta_numbers AS $key => $field) {
    $beta_number = '';

    // Generic $form_state['values']['submitted_tree']
    if (isset($form_values['submitted_tree']) && isset($form_values['submitted_tree'][$field][LANGUAGE_NONE][0])) {
      $beta_number = current($form_values['submitted_tree'][$field][LANGUAGE_NONE][0]);
    }

    // Security for the multiple form_state['values'] that we have migrating around the site.
    else if (isset($form_values[$field][LANGUAGE_NONE][0])) {
      $beta_number = current($form_values[$field][LANGUAGE_NONE][0]);
    }

    // Array of phone numbers passed to function
    if (dosomething_general_valid_cell($field)) {
      $beta_number = preg_replace('#[^0-9]#', '', $field);
    }

    // Check if valid cell and opt in to Mobile Commons.
    if (dosomething_general_valid_cell($beta_number)) {
      $valid_beta_numbers[] = $beta_number;

      $record = array(
        'alpha' => $alpha_number,
        'beta' => $beta_number,
        'timestamp' => REQUEST_TIME,
        'type' => $type,
        'nid' => $nid
      );

      drupal_write_record('sms_flow_records', $record);

      // Create and update the beta's Mobile Commons profile
      sms_mobile_commons_profile_update($beta_number, $beta_variables);
    }
  }

  // Opt-in alpha and beta to their respective paths
  dosomething_general_mobile_commons_subscribe_with_friends(
    $alpha_number,
    (!$beta_to_alpha_campaign ? $alpha_optin : $beta_to_alpha_campaign),
    $valid_beta_numbers,
    $beta_optin
  );
}

/**
 *  Accepts a phone number and returns the alpha who invited that phone number, if applicable.
 *
 *  @param $beta
 *    The beta's phone number.  Accepts with punctuation (e.g. xxx-xxx-xxxx) or without.
 *  @param $nid (optional...for now.)
 *    The node id that is being referenced.  This will ensure that we pull the correct alpha, when we
 *    have multiple flow types running at the same time.
 *  @param $type (optional)
 *    Type of invite being referenced. Possible some 'nid' values could overlap depending on the type.
 *
 *  @return the alpha's phone number, if applicable, or false.
 *
 *  Example:
 *  sms_flow_find_alpha('610-368-3195');
 */
function sms_flow_find_alpha($beta, $nid = 0, $type = '') {
  $beta_parsed = preg_replace('#[^0-9]#i', '', $beta);
  $select = db_query("
    SELECT alpha
    FROM sms_flow_records
    WHERE
       (beta = '" . $beta . "'
       OR beta = '" . $beta_parsed . "')
       " . ($nid > 0 ? "AND `nid` = " . intval($nid) : '') . "
       " . (!empty($type) ? "AND `type` = '" . $type . "'" : '') . "
    ORDER BY sid DESC
    LIMIT 1
  ");

  $r = current($select->fetchAll());
  return ($r->alpha ? $r->alpha : false);
}

/**
 *  Checks whether an alpha in the sms_flow_records table has received a message from
 *  an invited beta before, given a particular type and node ID.
 *
 *  @param int $alpha
 *    The phone number without ANY punctuation of the alpha.
 *
 *  @param int $nid
 *    The nid of the invitation, as found in the sms_flow_records table.
 *
 *  @param string $type
 *    The "type" of invitation, as seen in the sms_flow_records table.
 *
 *  @return boolean
 *    true if there is at least one message from beta -> alpha sent
 *    false if there have not been any messages sent from beta -> alpha
 */
function sms_flow_alpha_received_message($alpha, $nid, $type) {
  // Query the sms_flow_records table.
  $select = db_query("
    SELECT
      COUNT(*) AS sent
    FROM sms_flow_records
    WHERE `accepted_invite` = 1
      AND REPLACE(
        REPLACE(
          REPLACE(
            REPLACE(
              `alpha`, ')', ''
            ),
          '(', ''),
        ' ', ''),
      '-', '') = '" . $alpha . "'
      AND `type` = :type
      AND `nid` = :nid
  ", array(':type' => $type, ':nid' => $nid));

  // Get just what we need...
  $r = reset($select->fetchAll());

  // Return true if there's at least one response sent.
  return ($r->sent > 0);
}

/**
 *  Updates the "accepted invite" status for a particular beta number in the sms_flow_records table.
 *
 *  @param $alpha_number
 *    The number of the alpha user who sent the invite.
 *
 *  @param $beta_number
 *    The beta number to look up.
 *
 *  @param $nid
 *    The nid that the user is being invited to, as seen in the sms_flow_records table.
 *
 *  @param $type
 *    The type of invite to check against.
 *
 *  @return
 *    Returns true.
 */
function sms_flow_update_accepted_status($alpha_number, $beta_number, $nid, $type) {
  db_update('sms_flow_records')
    ->fields(array(
      'accepted_invite' => 1
    ))
    ->condition('alpha', $alpha_number)
    ->condition('beta', $beta_number)
    ->condition('nid', $nid)
    ->condition('type', $type)
    ->execute();

    return true;
}

/**
 * Create record in sms_flow_game table
 */
function sms_flow_game_create_record($phone, $game_id) {
  $phone = substr($phone, -10);

  $record = array(
    'phone' => $phone,
    'game_id' => $game_id,
    'started_paths' => '',
    'answers' => '',
  );

  $ret = drupal_write_record('sms_flow_game', $record);
}

/**
 * Return paths user's been sent to as an array
 */
function sms_flow_game_get_paths($phone, $game_id) {
  $phone = preg_replace('#[^0-9]#i', '', $phone);
  $phone = substr($phone, -10);

  $select = db_query("
    SELECT started_paths
    FROM sms_flow_game
    WHERE
       phone = '" . $phone . "'
       AND game_id = '" . $game_id . "'
    LIMIT 1
  ");

  $record = current($select->fetchAll());

  if ($record && !empty($record->started_paths)) {
    // Deserialize string into array
    $return = explode(',', $record->started_paths);
  } 

  return !empty($return) ? $return : array();
}

/**
 * Save paths user's been sent to to the sms_flow_game table
 */
function sms_flow_game_set_paths($phone, $game_id, $paths) {
  $phone = substr($phone, -10);

  // Serialize array before writing it to the database
  $serialized_paths = implode(',', $paths);

  db_update('sms_flow_game')
    ->fields(array(
      'started_paths' => $serialized_paths
    ))
    ->condition('phone', $phone)
    ->condition('game_id', $game_id)
    ->execute();
}

/**
 * Return answers from sms_flow_game as an associative array
 */
function sms_flow_game_get_answers($phone, $game_id) {
  $phone = preg_replace('#[^0-9]#i', '', $phone);
  $phone = substr($phone, -10);

  $select = db_query("
    SELECT answers
    FROM sms_flow_game
    WHERE
      phone = '" . $phone . "'
      AND game_id = '" . $game_id . "'
    LIMIT 1
  ");

  $record = current($select ->fetchAll());

  if ($record && !empty($record->answers)) {
    $return = json_decode($record->answers, true);
  }

  return !empty($return) ? $return : NULL;
}

/**
 * Convert answers from associative array to json string and save to sms_flow_game
 */
function sms_flow_game_set_answers($phone, $game_id, $answers) {
  $phone = substr($phone, -10);
  $serialized_answers = json_encode($answers);

  db_update('sms_flow_game')
    ->fields(array(
      'answers' => $serialized_answers
    ))
    ->condition('phone', $phone)
    ->condition('game_id', $game_id)
    ->execute();
}

/**
 * Implements hook_menu()
 */
function sms_flow_menu() {
  $items = array();

  $items['sms/sms_flow/%'] = array(
    'title' => 'Mobile Commons SMS Receiver for Invite Flow',
    'page callback' => 'sms_flow_incoming_callback',
    'access callback' => 'sms_mobile_commons_incoming_check',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Mimics functionality found in sms_mobile_commons_incoming_callback(). Allows for
 * for different endpoints to trigger different keyword paths
 */
function sms_flow_incoming_callback($path) {
  // Direct correlation between path endpoint and keyword used. If path doesn't match any keyword
  // specified in the array of keywords, then error out.
  $keyword = $path;
  $keyword_map = module_invoke_all('conductor_sms_keywords');
  if (!array_key_exists($path, $keyword_map)) {
    watchdog('sms_flow', "Received message at unsupported path: /sms/sms_flow/$path");
    return NULL;
  }

  // Using same code from sms_mobile_commons_incoming_callback(). Only difference
  // is $keyword gets set depending on the path found above.
  $message = isset($_REQUEST['args']) ? $_REQUEST['args'] : FALSE;
  $carrier = isset($_REQUEST['carrier']) ? $_REQUEST['carrier'] : FALSE;
  $sender = isset($_REQUEST['phone']) ? $_REQUEST['phone'] : FALSE;
  $gateway = sms_gateways('gateway', 'sms_mobile_commons');
  $config = $gateway['configuration'];
  $output = $config['sms_mobile_commons_response'];
  $context = array(
    'message' => $message,
    'keyword' => $keyword,
    'carrier' => $carrier,
    'sender' => $sender,
    'gateway' => $gateway,
  );
  drupal_alter('sms_mobile_commons_response', $output, $context);
  sms_incoming($sender, $message, array("carrier" => $carrier, 'keyword' => $keyword, 'response' => $output));
  if (!empty($output)) {
    $output =
    '<?xml version="1.0" encoding="UTF-8"?>
    <response>
     <reply>
      <text>
       <![CDATA[' . $output . ']]>
      </text>
     </reply>
    </response>';
    print $output;
  }

  return NULL;
}

/**
 * Merely for reference.  Not used because dosomething_general_mobile_commons_subscribe offers the same functionality.
 */
function sms_flow_mobile_commons_subscribe($mobile, $opt_in_path, $args = array()) {
  $api_opt_in_path_url = 'https://dosomething.mcommons.com/profiles/join';

  // Send the post data.
  $options = array(
    'headers' => array(
      'Content-type' => 'application/x-www-form-urlencoded',
      'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    ),
    'method' => 'POST',
    'data' => "person[phone]=$mobile&opt_in_path[]=$opt_in_path",
  );

  if (!empty($args)) {
    foreach ($args AS $key => $val) {
      $options['data'] .= "&person[$key]=" . urlencode($val);
    }
  }

  drupal_http_request($api_opt_in_path_url, $options);
}

/**
 * Helper function to find all files within a directory that end with the given extension
 */
function _sms_flow_list_files_by_extension($dir, $file_ext, &$matching_files) {
  $files = scandir($dir);
  foreach ($files as $file) {
    if ($file != '.' && $file != '..') {
      $path = $dir . '/' . $file;

      if (is_dir($path)) {
        _sms_flow_list_files_by_extension($path, $file_ext, $matching_files);
      }
      elseif (preg_match('/'  . $file_ext . '$/', $path) === 1) { 
        $matching_files[] = $path;
      }
    }
  }
}

/**
 * Specifies conductor workflows that should trigger for a given endpoint
 *   [endpoint] => [conductor workflow]
 */
function sms_flow_conductor_sms_keywords() {
  $keywords = array();

  // Find files in this directory tree with the .keywords.inc extension and
  // include them to populate the keywords array.
  $files = array();
  _sms_flow_list_files_by_extension(dirname(__FILE__), '.keywords.inc', $files);

  foreach ($files as $file) {
    include $file;
  }

  return $keywords;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function sms_flow_ctools_plugin_api($owner, $api) {
  if ($owner == 'conductor') {
    return array('version' => 1.0);
  }
}

/**
 * Implements hook_ctools_plugin_directory
 */
function sms_flow_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'conductor') {
    return "plugins/$plugin_type";
  }
}

/**
 * Implements hook_default_conductor_workflows().
 * Searches for local .workflows.inc files for instantiated ConductorWorkflows to add to array
 */
function sms_flow_default_conductor_workflows() {
  $workflows = array();

  // Find files in this directory tree with the .workflows.inc extension and
  // include them to populate the workflows array.
  $files = array();
  _sms_flow_list_files_by_extension(dirname(__FILE__), '.workflows.inc', $files);

  foreach ($files as $file) {
    include $file;
  }

  return $workflows;
}

function sms_flow_team_invite_form($form, &$form_state, $gid, $alpha_optin = 0, $beta_optin = 0) {
  $form['alpha'] = array(
    '#type' => 'textfield',
    '#title' => 'Your Cell Number:',
    '#size' => 16,
  );

  $form['beta0'] = array(
    '#type' => 'textfield',
    '#title' => 'Friends\' Cell Numbers:',
    '#size' => 16,
  );
  $form['beta1'] = array(
    '#type' => 'textfield',
    '#size' => 16,
  );
  $form['beta2'] = array(
    '#type' => 'textfield',
    '#size' => 16,
  );
  $form['beta3'] = array(
    '#type' => 'textfield',
    '#size' => 16,
  );
  $form['beta4'] = array(
    '#type' => 'textfield',
    '#size' => 16,
  );

  $form['invite-gid'] = array(
    '#type' => 'hidden',
    '#default_value' => $gid,
    '#value' => $gid,
  );

  $form['alpha-optin'] = array(
    '#type' => 'hidden',
    '#default_value' => 0,
    '#value' => $alpha_optin,
  );

  $form['beta-optin'] = array(
    '#type' => 'hidden',
    '#default_value' => 0,
    '#value' => $beta_optin,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Invite',
  );

  return $form;
}

function sms_flow_team_invite_form_submit($form, &$form_state) {
  global $user;
  $profile = profile2_load_by_user($user, 'main');
  if ($profile) {
    $inviter = $profile->field_user_first_name[LANGUAGE_NONE][0]['value'];
  }

  if (empty($inviter)) {
    $inviter = $form_state['values']['alpha'];
  }

  $alpha_mobile = $form_state['values']['alpha'];
  $beta_numbers = array();
  for ($i = 0; $i < 5; $i++) {
    $element_name = 'beta' . $i;
    if (!empty($form_state['values'][$element_name])) {
      $beta_numbers[] = $form_state['values'][$element_name];
    }
  }

  $alpha_optin = $form_state['values']['alpha-optin'];
  $beta_optin = $form_state['values']['beta-optin'];
  $invite_gid = $form_state['values']['invite-gid'];
  // TODO: sms_flow_start expects NID value to be here. Might want to consider modifying that
  $form_state['values']['details']['nid'] = $invite_gid;

  if (count($beta_numbers) > 0) {
    sms_flow_start($alpha_mobile, $alpha_optin, $beta_optin, $beta_numbers, $form_state['values'], array(
        'tfj2013_inviter' => $inviter,  // TODO: should remove this eventually when TFJ is done
        'drives_inviter' => $inviter,
        'drives_invite_gid' => $invite_gid,
      )
    );
  }

}

/**
 * Returns the already existing Drupal user for the given mobile number, or 
 * creates one to then return.
 */
function sms_flow_get_or_create_user_by_cell($mobile) {
  $account = dosomething_api_user_lookup($mobile);
  if (!$account) {
    $account = new stdClass;
    $account->name = $mobile;

    $suffix = 0;
    $base_name = $account->name;
    while (user_load_by_name($account->name)) {
      $suffix++;
      $account->name = $base_name . '-' . $suffix;
    }
    $account->mail = $mobile . '@mobile';
    $account->status = 1;

    $account = user_save($account);

    $profile_values = array('type' => 'main');
    $profile = profile2_create($profile_values);
    $profile->uid = $account->uid;
    $profile->field_user_mobile[LANGUAGE_NONE][0]['value'] = $mobile;

    try {
      profile2_save($profile);
    }
    catch( Exception $e ) {
      watchdog('sms_flow', "Failed to save newly created profile. m:$mobile / uid:$profile->uid / name:$account->name");
      return NULL;
    }
  }

  return $account;
}