<?php

include_once 'dosomething_grant_judging.features.inc';

/**
 * Implements hook_page_alter().
 */
function dosomething_grant_judging_page_alter(&$page) {
  global $user;
  // If logged in user is viewing a Seed Grants submission:
  if ($user->uid > 0 && drupal_match_path(current_path(), 'node/718444/submission/*' . PHP_EOL)) {
    // If user is product team or admin, display Manage Grants tab:
    if (module_exists('dosomething_admin') && dosomething_admin_is_current_user_role('product team')) {
      // Grab current path to use as destination for all links:
      $destination = array('query' => array('destination' => current_path()));
      // HACK THE PLANET:
      $manage_grants = "<div><p>" . l("All Grant Submissions", 'node/718444/webform-results') . 
      " | <strong>Add to Queue:</strong> " . l('Judging', 'admin/structure/entityqueue/manage/grants_judging', $destination) . ' | ' . l('Too Soon Apply Later', 'admin/structure/entityqueue/manage/grants_toosoon', $destination) . ' | ' . l('No List', 'admin/structure/entityqueue/manage/grants_rejected', $destination)  . '</p></div>';
      // Add manage grants div into content #submission_navigation.
      $page['content']['system_main']['#submission_navigation'] = $manage_grants . $page['content']['system_main']['#submission_navigation'];
    }
  }
}

/**
 * Implements hook_user_presave().
 */
function dosomething_grant_judging_user_presave(&$edit, $account, $category) {
  if (isset($account->is_new) && !empty($account->is_new)) {
    // set the role to add to someone's profile for grant judging
    $grant_role = variable_get('dosomething_grant_judging_role', 5);

    // domain addresses to auto-promote to grant reviewer
    $grant_domains = array(
      'aexp.com',
      'dosomething.org',
    );

    // get the domain of the user emails
    $domain = explode('@', $account->mail);
    $domain = $domain[count($domain)-1];

    // if they have an email from this domain
    if (in_array($domain, $grant_domains)) {
      $roles = user_roles(TRUE);
      if (!isset($edit['roles'])) {
        $edit['roles'] = array();
      }

      // append the user role to any currently added roles
      $edit['roles'] = $edit['roles'] + array($grant_role => $roles[$grant_role]);
    }
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function dosomething_grant_judging_ctools_plugin_type() {
  return array(
    'grant_judge_form' => array(
      'cache' => TRUE,
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * @param string $owner
 *   The system name of the module owning the plugin type for which a base
 *   directory location is being requested.
 * @param string $plugin_type
 *   The name of the plugin type for which a base directory is being requested.
 * @return string
 *   The path where CTools' plugin system should search for plugin files,
 *   relative to your module's root. Omit leading and trailing slashes.
 */
function dosomething_grant_judging_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}
