<?php
/**
 * @file
 * Code for the dosomething_webform feature.
 */

include_once('dosomething_webform.features.inc');

/**
 * Implements hook_node_load().
 */
function dosomething_webform_node_load($nodes, $types) {
  foreach ($nodes as $node) {
    // Suppress all 'You have already submitted this form' messages.
     if (isset($node->webform)) {
       $node->webform['submit_notice'] = 0;
     }
  }
}
