<?php

/**
 * @file
 * Provide mobile commons integration for SMS framework.
 */


function sms_mobile_commons_admin_page() {
  $form = array(
    'email' => array(
      '#weight' => 0,
      '#type' => 'textfield',
      '#title' => t('Mobile Commons Email Account'),
      '#description' => t('Mobile Commons uses an email address as a user name 
        for authentication. Enter this email address here.'),
      '#default_value' => '',
      '#required' => TRUE,
      '#size' => 60,
      '#maxlength' => 255,
    ),
    'password' => array(
      '#weight' => 0,
      '#type' => 'password',
      '#title' => t('Mobile Commons password'),
      '#description' => t('The password associated with the Mobile Commons 
        account.'),
      //No need to pull the password back. We shouldn't show it.
      '#default_value' => '',
      '#required' => TRUE,
      '#size' => 60, 
      '#maxlength' => 255,
    ),
    'url' => array(
      '#weight' => 0,
      '#type' => 'textfield',
      '#title' => t('Mobile Commons custom URL'),
      '#description' => t('Each mobile commons account has a custom URL for 
        accessing information and sending data requests. This usually looks 
        like "http://MYSITE/mcommons.com".'),
      '#default_value' => '',
      '#required' => TRUE,
      '#size' => 60, 
      '#maxlength' => 255,
    ),
    'campaign_id' => array(
      '#weight' => 0,
      '#type' => 'textfield',
      '#title' => t('Campaign ID'),
      '#description' => t('People you plan to send SMS messages to need to be 
        part of a Mobile Commons campaign. Campains have a campaign ID number.'),
      '#default_value' => '',
      '#required' => TRUE,
      '#size' => 10, 
      '#maxlength' => 20,
    ),
    'submit' => array(
      '#weight' => 10,
      '#type' => 'submit',
      '#value' => t('Submit'),
    ),
  );
  return $form;
}

/**
 * Custom callback for incoming HTTP request.
 */
function sms_mobile_commons_incoming_callback() {  
  $message = $_REQUEST['args'];  
  $keyword = $_REQUEST['keyword'];
  $carrier = $_REQUEST['carrier'];
  $keyword = $_REQUEST['keyword'];
  $sender = $_REQUEST['phone'];

  watchdog('sms_mobile_commons', 'Received message from %sender: %message', array('%sender' => $sender, '%message' => $message));
  sms_incoming($sender, $message, array("carrier" => $carrier, 'keyword' => $keyword));
  watchdog('sms_mobile_commons', 'Received message ' . serialize($_SERVER));
}

/**
 * Implements hook_menu().
 */
function sms_mobile_commons_menu() {
  $items = array();

  $items['sms/mobile-commons/receiver'] = array(
    'title' => 'Mobile Commons SMS receiver',
    'page callback' => 'sms_mobile_commons_incoming_callback',
    'access callback' => 'sms_mobile_commons_incoming_check',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Add a filter to ensure incoming texts are coming from Mobile Commons' IP.
 */
function sms_mobile_commons_incoming_check() {
  if ($_SERVER['REMOTE_ADDR'] == "64.22.127.76") {
    return TRUE;
  }
  return FALSE;
}