<?php

/**
 * @file
 * Array of endpoints ("keywords") and the name of the workflows they are each
 * associated with. Keyword/workflow pairs here are for the MLK/Activist Text game.
 */
$keywords['mlk-invite-end-game'] = 'sms_flow_mlk_invite_end_game';
$keywords['mlk-invite-path-1'] = 'sms_flow_mlk_invite_path_1';
$keywords['mlk-invite-path-2'] = 'sms_flow_mlk_invite_path_2';
$keywords['mlk-invite-path-3'] = 'sms_flow_mlk_invite_path_3';
$keywords['mlk-invite-path-4'] = 'sms_flow_mlk_invite_path_4';
$keywords['mlk-process-beta'] = 'sms_flow_mlk_process_beta';
