<?php
/**
 * @file
 * Code for the dosomething_user_my_somethings feature.
 */

include_once('dosomething_user_my_somethings.features.inc');

/**
* Implementation of hook_ctools_plugin_directory().
*/
function dosomething_user_my_somethings_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_webform_submission_insert().
 */
function dosomething_user_my_somethings_webform_submission_insert($node, $submission) {
  cache_clear_all('dosomething_user_my_somethings_' . $submission->uid, 'cache');
}

/**
 * Implements hook_webform_submission_update().
 */
function dosomething_user_my_somethings_webform_submission_update($node, $submission) {
  cache_clear_all('dosomething_user_my_somethings_' . $submission->uid, 'cache');
}

/**
 * Implements hook_og_membership_insert().
 */
function dosomething_user_my_somethings_og_membership_insert($membership) {
  if ($membership->entity_type == 'user') {
    cache_clear_all('dosomething_user_my_somethings_' . $membership->etid, 'cache');
  }
}

/**
 * Member dashboard block for logged in users.
 */
function dosomething_user_my_somethings_member_block() {
  global $user;
  return array(
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'dosomething_user_my_somethings') . '/js/show-member-items.js',
      ),
    ),
    'name' => array(
      '#type' => 'container',
      '#prefix' => '<a href="/user" class="ds-member-name-bar">',
      '#suffix' => '</a>',
      '#attributes' => array(
        'class' => array(
          'dosomething-login-user-name',
        ),
      ),
      'name' => array(
        '#prefix' => '<h2>',
        '#suffix' => '</h2>',
        '#markup' => dosomething_general_get_full_name($user, 'private'),
      ),
      // 'role' => array(
        // '#prefix' => '<span class="user-role">( ',
        // '#suffix' => ' )</span>',
        // '#markup' => dosomething_user_my_somethings_user_role(),
      // ),
    ),
    'collapsible' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'dosomething-user-block-collapsible',
        ),
      ),
      'profile' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'dosomething-login-profile',
          ),
        ),
        'completion' => dosomething_user_my_somethings_profile_completion(),
      ),
      'somethings' => dosomething_user_my_somethings_my_somethings(),
      'clubs' => dosomething_user_my_somethings_clubs(),
    ),
  );
}

/**
 * Markup for how much of the profile is finished.
 */
function dosomething_user_my_somethings_profile_completion($account = FALSE, $sidebar = TRUE) {
  if (!$account) {
    global $user;
    $account = clone $user;
  }
  $ratio = 0;
  if (module_exists('dosomething_roles')) {
    $ratio = dosomething_roles_get_user_percentage($account->uid);
  }

  $complete_text = !empty($sidebar) ? 'Profile %percent complete' : '%percent complete';

  return array(
    'percentage' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'dosomething-login-percentage',
        ),
      ),
      'ratio' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'ratio',
          ),
          'data-ratio' => $ratio,
        ),
        'inner' => array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array(
              'inner',
            ),
            'style' => 'width: ' . $ratio . '%',
          ),
        ),
        'label' => array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array(
              'label',
            ),
          ),
          '#children' => t($complete_text, array('%percent' => number_format($ratio, 0) . '%')),
        ),
      ),
    ),
    'footer' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'profile-footer',
        ),
      ),
      'complete-profile' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'complete-profile',
          ),
        ),
        '#children' => t('Complete your profile now'),
      ),
      'complete-link' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'complete-link',
          ),
        ),
        '#children' => l('Go', 'user/' . $account->uid . '/complete-profile'),
      ),
    ),
  );
}

/**
 * Get markup for my somethings (sidebar version). Renamed 'Doing It' for theming purposes.
 */
function dosomething_user_my_somethings_my_somethings() {
  global $user;
  $items = array();

  $items = dosomething_user_my_somethings_my_current_something_links($user->uid);

  return array(
    'title' => array(
      '#prefix' => '<h3 class="doing-it">',
      '#suffix' => '</h3>',
      'inner' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => 'inner',
        ),
        '#children' => t('Doing It'),
      ),
    ),
    'list' => array(
      '#theme' => 'item_list',
      '#items' => $items,
      '#attributes' => array(
        'class' => array(
          'doing-it',
        ),
      ),
    ),
  );
}

/**
 * Get a list of links for the different types of my somethings.
 * This populates the sidebar list of 'my current somethings'.
 *
 * @param $uid
 *  (int) a user id.
 * @return array
 */
function dosomething_user_my_somethings_my_current_something_links($uid) {
  $items = array();
  $account = user_load($uid);

  $cid = 'dosomething_user_my_somethings_' . $uid;
  $cache = cache_get($cid);

  $somethings_info = array(
    'grant_application' => array(
      'title' => t('Grant Applications'),
      'title_field' => 'field_webform_name',
    ),
    'project_report' => array(
      'title' => t('Project Reports'),
      'title_field' => 'field_project_title',
    ),
  );

  if (!is_object($cache) || !isset($cache->data['somethings'])) {
    $somethings = dosomething_user_my_somethings_get_my_somethings($uid, 'current');
    if (!is_object($cache)) {
      $cache = new stdClass();
      $cache->data = array();
    }
    $cache->data['somethings'] = $somethings;
    cache_set($cid, $cache->data);
  }
  else {
    $somethings = $cache->data['somethings'];
  }

  if (count($somethings)) {
    foreach ($somethings as $type => $something) {
      if (count($something)) {
        $items[$type] = array('data' => $somethings_info[$type]['title'], 'children' => array());
        foreach ($something as $submission) {
          // Note: This is not an actual submission object, but it has the right
          // info, so we're not loading it up as of now.
          $title = filter_xss($submission->{$somethings_info[$type]['title_field'] . '_value'});
          $node = node_load($submission->nid);
          $edit_access = webform_submission_access($node, $submission, 'edit', $account);
          $link = $edit_access ? "node/{$node->nid}/submission/{$submission->sid}/edit" : 'webform-submission/' . $submission->sid;
          $items[$type]['children'][] = l($title, $link);
        }
      }
    }
  }

  if (!is_object($cache) || !isset($cache->data['report_backs'])) {
    $report_backs = dosomething_user_my_somethings_campaign_report_backs_needed($uid);
    if (!is_object($cache)) {
      $cache = new stdClass();
      $cache->data = array();
    }
    $cache->data['report_backs'] = $report_backs;
    cache_set($cid, $cache->data);
  }
  else {
    $report_backs = $cache->data['report_backs'];
  }

  if (count($report_backs)) {
    $items['campaign_report_back'] = array('data' => 'Campaign Sign Ups', 'children' => array());
    foreach($report_backs as $report_back) {
      $items['campaign_report_back']['children'][] = l($report_back->campaign_title, 'node/' . $report_back->report_back_entity_id);
    }
  }
  return $items;
}

/**
 * Get the markup for a list of user's clubs (sidebar version). Renamed 'Done It' for theming purposes.
 */
function dosomething_user_my_somethings_clubs($account = NULL) {
  global $user;
  if (empty($account)) {
    $account = clone $user;
  }
  $items = array();

  // TODO: It would be nice to cache these memberships.
  $groups = dosomething_user_my_somethings_get_user_group_memberships($account->uid, 'club');
  if (count($groups)) {
    foreach ($groups as $group) {
     $items[] = l(filter_xss($group->title), 'node/' . $group->nid);
    }
  }
  else {
    $items[] = l(t('Start a club'), 'node/add/club');
  }

  return array(
    'title' => array(
      '#prefix' => '<h3 class="done-it">',
      '#suffix' => '</h3>',
      'inner' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => 'inner',
        ),
        '#children' => t('Done It'),
      ),
    ),
    'list' => array(
      '#theme' => 'item_list',
      '#items' => $items,
      '#attributes' => array(
        'class' => array(
          'done-it',
        ),
      ),
    ),
  );
}

/**
 * Show the user's role.
 */
function dosomething_user_my_somethings_user_role($account = NULL) {
  if (!isset($account)) {
    global $user;
    $account = $user;
  }
  if (dosomething_roles_user_is_staff_member($account)) {
    return t('staff');
  }
  $current_role = dosomething_roles_get_current_role($account->uid);
  $exploded_role = explode(' ', trim($current_role));
  return filter_xss($exploded_role[0]);
}

/**
 * Get a list of a user's webform submissions.
 *
 * @param $uid
 *  (int) a user id.
 * @param $type
 *  (string) The type of weform submission.
 * @param $title_field
 *  (string) The name of the title field for the webform type.
 * @param $is_draft
 *  (boolean_ Whether or not the submission is a draft.
 * @param $statuses
 *  (array) A list of statuses for filtering on project reports.
 * @return array
 */
function dosomething_user_my_somethings_get_submissions($uid, $type, $title_field, $is_draft = FALSE, $statuses = NULL) {
  $submissions = array();
  if (is_array($statuses)) {
    $available_statuses = array(
      2 => 'project idea',
      3 => 'ongoing project',
      4 => 'completed project',
    );
    $statuses = array_keys(array_intersect($available_statuses, $statuses));
  }
  try {
    $query = db_select('webform_submissions', 'ws');
    $query->innerJoin('node', 'n', 'ws.nid = n.nid');
    $query->innerJoin('field_data_' . $title_field, 't', 'ws.sid = t.entity_id');
    if (is_array($statuses)) {
     $query->innerJoin('field_data_field_project_type', 'pt', 'ws.sid = pt.entity_id');
    }
    $query->fields('ws', array('sid', 'submitted', 'uid', 'is_draft'));
    $query->fields('n', array('nid', 'type'));
    $query->fields('t', array($title_field . '_value'));
    $query->condition('ws.uid', $uid, '=');
    $query->condition('n.type', $type, '=');
    $query->condition('ws.is_draft', (int) $is_draft, '=');
    $query->condition('t.entity_type', 'webform_submission_entity', '=');
    if (is_array($statuses)) {
      $query->condition('pt.entity_type', 'webform_submission_entity', '=');
      $query->condition('pt.field_project_type_value', $statuses, 'IN');
    }
    $results = $query->execute();
    while ($result = $results->fetchObject()) {
      $submissions[$result->sid] = $result;
    }
  }
  catch (Exception $e) {
    return NULL;
  }
  return $submissions;
}

/**
 * Get a list of group memberships for a user based on node type.
 *  of group.  This assumes that the group is a node and the membership
 *  is for a user.
 */
function dosomething_user_my_somethings_get_user_group_memberships($uid, $node_type) {
  if (!module_exists('og')) {
    continue;
  }
  // There doesn't seem to be an og function to do exactly what we want
  // so we have our own.
  $groups = array();
  $query = db_select('og_membership', 'm');
  $query->innerJoin('og', 'o', 'o.gid = m.gid');
  $query->innerJoin('node', 'n', 'o.etid = n.nid');
  $query->fields('o', array('gid', 'etid'));
  $query->fields('n', array('nid', 'title'));
  $query->condition('o.entity_type', 'node', '=');
  $query->condition('m.etid', $uid, '=');
  $query->condition('n.type', $node_type, '=');
  $query->condition('o.state', OG_STATE_ACTIVE);
  $results = $query->execute();
  while ($result = $results->fetchObject()) {
    $groups[$result->etid] = $result;
  }
  return $groups;
}

/**
 * Build list of current/past somethings. These include:
 *   Grant applications (link to grant application form)
 *   Projects (links to project update form)
 *
 * @param $uid
 *  (int) a user id.
 * @param $era
 * (string) 'current' or 'past' somethings. 
 * @return array
 */
function dosomething_user_my_somethings_get_my_somethings($uid, $era) {
  $somethings_info = array(
    'grant_application' => array(
      'title_field' => 'field_webform_name',
      'draft' => $era == 'current' ? TRUE : FALSE,
      'statuses' => NULL,
    ),
    'project_report' => array(
      'title_field' => 'field_project_title',
      'draft' => FALSE,
      'statuses' => $era == 'current' ? array('ongoing project', 'project idea') : array('completed project'),
    ),
  );

  foreach ($somethings_info as $type => $info) {
    $somethings[$type] = dosomething_user_my_somethings_get_submissions($uid, $type, $info['title_field'], $info['draft'], $info['statuses']);
  }

  return $somethings;
}

/**
 * Implements hook_theme().
 */
function dosomething_user_my_somethings_theme() {
  return array(
    'dosomething_profile_info' => array(
      'template' => 'ds-profile-info',
      'variables' => array(
        'profile' => new stdClass,
        'account' => new stdClass,
        'dosomething_friends' => '',
      ),
    )
  );
}

/**
 * Get a list of campain report backs that a user has not submitted
 * for that user's campaign groups.
 */
function dosomething_user_my_somethings_campaign_report_backs_needed($uid) {
  $gids = array();
  $report_backs = array();
  $report_backs_entity_ids = array();
  $user_submissions = array();
  $incomplete_report_backs = array();

  if ($groups = dosomething_user_my_somethings_get_user_group_memberships($uid, 'campaign')) {
    foreach ($groups as $group) {
      $gids[] = $group->gid;
    }

    // Check that a campaign report back exists for each user's campaign.
    // Get campaign title and entity_id of that campaign's report back.
    $query = db_select('og_membership', 'om');
    $query->innerJoin('og', 'o', 'om.gid = o.gid');
    $query->innerJoin('node', 'n', 'om.etid = n.nid');
    $query->addField('om', 'etid', 'report_back_entity_id');
    $query->addField('o', 'etid', 'campaign_entity_id');
    $query->addField('o', 'label', 'campaign_title');
    $query->condition('n.type', 'campaign_report_back', '=');
    $query->condition('o.gid', $gids, 'IN');
    $results = $query->execute();
    while ($result = $results->fetchObject()) {
      $report_backs[] = $result;
      $report_backs_entity_ids[] = $result->report_back_entity_id;
    }

    if (count($report_backs_entity_ids)) {
      // From these existing campaign report backs, get the user's submissions.
      $db_query = db_select('webform_submissions', 'w');
      $db_query->fields('w', array('nid'));
      $db_query->condition('w.uid', $uid, '=');
      $db_query->condition('nid', $report_backs_entity_ids, 'IN');
      $results = $db_query->execute();
      while ($result = $results->fetchObject()) {
        $user_submissions[] = $result->nid;
      }
    }

    // Check if user has a submission for each report back,
    // if not return that info.
    foreach ($report_backs as $report_back) {
      if (!in_array($report_back->report_back_entity_id, $user_submissions)) {
        $incomplete_report_backs[$report_back->report_back_entity_id] = $report_back;
      }
    }
  }
  return $incomplete_report_backs;
}

/**
 * Get a list of campaign report backs completed by user.
 */
function dosomething_user_my_somethings_campaign_report_backs_complete($uid) {
  $report_backs = db_query("SELECT DISTINCT(o.etid) as campaign_entity_id FROM {webform_submissions} w
                            INNER JOIN {og_membership} om ON w.sid = om.etid
                            INNER JOIN {og} o ON om.gid = o.gid
                            WHERE w.bundle = 'campaign_report_back' AND o.entity_type = 'node' AND w.uid = :uid", 
                            array(':uid' => $uid))->fetchAll();
  return $report_backs;
}

/**
 * Implements hook_preprocess_dosomething_profile_info().
 */
function dosomething_user_my_somethings_preprocess_dosomething_profile_info(&$variables) {
  // Extract the user and profile objects.
  $account = $variables['account'];

  if($variables['profile']) {
    $profile = entity_metadata_wrapper('profile2', $variables['profile']);
  }

  $variables['member_fullname'] = dosomething_general_get_full_name($account, 'private');
  $variables['member_status'] = dosomething_user_my_somethings_user_role($account);
  $variables['member_since'] = date('m/d/Y', $account->created);
  $variables['member_clubs'] = dosomething_user_my_somethings_clubs($account);
  $variables['member_clubs']['title']['#access'] = FALSE;
  $profile_completion = dosomething_user_my_somethings_profile_completion($account, FALSE);
  $variables['member_percentage'] = $profile_completion['percentage'];
  $variables['member_vitals'] = dosomething_user_my_somethings_counter($account->uid);
  // Don't show a user picture if there isn't one in the account.
  $picture = array(
    '#theme' => 'image_formatter',
    '#item' => array(
      'alt' => t('Member Profile Picture'),
      'title' => '',
    ),
  );
  if (isset($account->picture)) {
    $picture['#image_style'] = 'action_results_thumbnail';
    $picture['#item']['uri'] = $account->picture->uri;
  }
  else {
    $link = fboauth_action_link_properties('ds_connect');
    $picture['#item']['uri'] = drupal_get_path('module', 'dosomething_user_my_somethings') . '/member-connect.png';
    $picture['#path'] = array(
      'path' => $link['href'],
      'options' => $link,
    );
  }
  $variables['member_picture'] = $picture;

  // Check to see if the profile object was loaded, if not, assign some junk
  // values to prevent the user page from blowing up.
  // NOTE: is_object($profile) complains that $profile is not a variable while
  // isset($profile) does not.
  if (isset($profile)) {
    $address = $profile->field_user_address->value();
    $variables['member_school'] = $profile->field_school_reference->value();
  }
  else {
    $address = "n/a";
    $variables['member_school'] = "n/a";
  }

  // Build the hometown value out of city and state.
  // Check to see if the profile object was loaded, if not, assign some
  $variables['hometown'] = dosomething_user_my_somethings_hometown($address);
}

function dosomething_user_my_somethings_hometown($address) {
  $hometown = array(
    $address['locality'],
    $address['administrative_area'],
  );
  $hometown = implode(', ', array_filter($hometown));
  if (empty($hometown)) {
    $hometown = '-';
  }
  return check_plain($hometown);
}


/**
 * Get data for /user campaign report backs for current and past my somethings.
 */
function dosomething_user_my_somethings_campaign_list($uid, $era) {
  $somethings = array();
  if ($era == 'current') {
    $campaigns = dosomething_user_my_somethings_campaign_report_backs_needed($uid);
  }
  elseif ($era == 'past') {
    $campaigns = dosomething_user_my_somethings_campaign_report_backs_complete($uid);
  }
  if ($campaigns) {
    foreach ($campaigns as $campaign) {
      $something = new stdClass();
      if (isset($campaign->report_back_entity_id)) {
        $report_back = node_load($campaign->report_back_entity_id);
        $something->uri = entity_uri('node', $report_back);
      }
      $campaign = node_load($campaign->campaign_entity_id);
      if (!isset($something->uri)) {
        $something->uri = entity_uri('node', $campaign);
      }
      $image = field_get_items('node', $campaign, 'field_campaign_main_image');
      $something->image = isset($image[0]['uri']) ? $image[0] : NULL;
      $something->title = $campaign->title;
      $something->type = 'campaign';
      $somethings[] = $something;
    }
  }
  return $somethings;
}

/**
 * Get data for projects and grant applications for /user current and past my somethings.
 */
function dosomething_user_my_somethings_projects_grants_list($uid, $era) {
  $somethings = array();
  $account = user_load($uid);
  $types = dosomething_user_my_somethings_get_my_somethings($uid, $era); // gives project reports and grant apps
  if (count($types)) {
    foreach ($types as $type => $data) {
      if ($type == 'grant_application') {
        if (count($data)) {
          foreach ($data as $grant_app) {
            $submissions = entity_load('webform_submission_entity', array($grant_app->sid));
            $submission = array_shift($submissions);
            $grant_ref = field_get_items('webform_submission_entity', $submission, 'field_webform_grant_ref');
            // Note if the grant application does not reference a grant, it will not be listed.
            if (isset($grant_ref[0]['nid'])) {
              $grant = node_load($grant_ref[0]['nid']);
              $image = field_get_items('node', $grant, 'field_picture');
              $something = new stdClass();
              $something->image = isset($image[0]['uri']) ? $image[0] : NULL;
              $node = node_load($submission->nid);
              $edit_access = webform_submission_access($node, $submission, 'edit', $account);
              $something->uri = array('options' => array());
              $something->uri['path'] = ($edit_access && $era == 'current') ? "node/{$node->nid}/submission/{$submission->sid}/edit" : 'webform-submission/' . $submission->sid;
              $something->title = $grant->title;
              $something->type = 'grant_application';
              $somethings[] = $something;
            }
          }
        } 
      }
      elseif ($type == 'project_report') {
        if (count($data)) {
          foreach ($data as $project) {
            $submissions = entity_load('webform_submission_entity', array($project->sid));
            $submission = array_shift($submissions);
            $image = field_get_items('webform_submission_entity', $submission, 'field_picture');
            $something = new stdClass();
            $something->image = isset($image[0]['uri']) ? $image[0] : NULL;
            $something->uri = entity_uri('webform_submission_entity', $submission);
            $something->check_path = TRUE;
            $title = field_get_items('webform_submission_entity', $submission, 'field_project_title');
            $something->title = isset($title[0]['value']) ? $title[0]['value'] : t('New Project');
            $something->type = 'project_report';
            $somethings[] = $something;
          }
        }
      }
    }
  }
  return $somethings;
}

/**
 * Content for the current somethings and past somethings panes.
 */
function dosomething_user_my_somethings_display($uid, $era = 'current', $all = TRUE) {
  $cid = 'dosomething_user_my_somethings_' . $uid;
  $cache = cache_get($cid);
  if (!is_object($cache) || !isset($cache->data[$era])) {
    $campaigns = dosomething_user_my_somethings_campaign_list($uid, $era);
    $somethings = dosomething_user_my_somethings_projects_grants_list($uid, $era);
    $all_somethings = array_merge($campaigns, $somethings);
    if (!is_object($cache)) {
      $cache = new stdClass();
      $cache->data = array();
    }
    $cache->data[$era] = $all_somethings;
    cache_set($cid, $cache->data);
  }
  else {
    $all_somethings = $cache->data[$era];
  }
  if (!count($all_somethings)) {
    switch ($era) {
      case 'current':
        $empty_text = t('You are not doing anything. Join a campaign, or start a grant application or project!');
        break;
      case 'past':
        $empty_text = t('You have not done anything. Complete a campaign report back, or finish a grant application or project!');
        break;
    }
    $element = array(
      '#type' => 'markup',
      '#markup' => $empty_text,
      '#prefix' => '<p>',
      '#suffix' => '</p>',
    );
  }
  else {
    if ($all) {
      $image_style = 'my_somethings';
      $more_link = '';
    }
    else {
      if (count($all_somethings) > 4) {
        $path = ($era == 'current') ? 'doing-it' : 'done-it';
        $more_link = l('More »', 'user/' . $uid . '/' . $path);
      }
      $all_somethings = array_slice($all_somethings, 0, 4);
      $image_style = 'project_related_thumb';
    }

    foreach ($all_somethings as $delta => $something) {
      // Set default access for the edit link to FALSE.
      $edit_access = FALSE;
      // Some webform submissions need a conditional path.
      // We don't want it cached, so we add a flag to check the path.
      // We can expand this if there are more pieces that have conditional paths.
      if (isset($something->check_path) && $something->check_path && $era == 'current') {
        if (module_exists('dosomething_projects_general') && $something->uri['options']['entity_type'] = 'webform_submission_entity') {
          $submission = $something->uri['options']['entity'];
          $node = node_load($submission->nid);
          $edit_access = webform_submission_access($node, $submission, 'edit');
        }
      }
      $element[$delta] = array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'views-row',
          ),
        ),
        'image' => array(
          '#theme' => 'image_formatter',
          '#item' => $something->image,
          '#image_style' => $image_style,
          '#path' => array(
            'path' => $something->uri['path'],
            'options' => $something->uri['options'] + array(
              'attributes' => array(
                'class' => array('pane-narrow-thumb'),
              ),
            ),
          ),
        ),
        'description' => array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array(
              'something-description',
            ),
          ),
          'title' => array(
            '#type' => 'link',
            '#title' => t($something->title),
            '#href' => $something->uri['path'],
            '#prefix' => '<div class="views-field-title">',
            '#suffix' => '</div>',
          ),
        ),
      );
      if ($edit_access) {
        $element[$delta]['description']['complete-this']['#href'] = "node/{$node->nid}/submission/{$submission->sid}/edit";
      }
    }
    $element['more'] = array(
      '#prefix' => '<span class="more-link-right">',
      '#suffix' => '</span>',
      '#markup' => $more_link,
    );
  }
  return $element;
}

/**
 * Returns themed user profile counter.
 */
function dosomething_user_my_somethings_counter($uid) {
  $campaigns = dosomething_user_my_somethings_campaign_report_backs_complete($uid);
  $campaigns_completed = count($campaigns);

  $projects = dosomething_user_my_somethings_get_submissions($uid, 'project_report', 'field_project_title');
  $projects_uploaded = count($projects);

  $items = array();
  $items['campaigns_completed'] = array(
    'title' => t('Campaigns Completed'),
    'value' => $campaigns_completed,
  );
  $items['projects_uploaded'] = array(
    'title' => t('Projects Uploaded'),
    'value' => $projects_uploaded,
  );

  return theme('dosomething_stats_counter', array('items' => $items));
}

/*
 * Content for stuff you need to do and stuff you've done.
 */
function dosomething_user_my_somethings_stuff_need_display($uid, $era = 'current') {
  $cid = 'dosomething_user_my_somethings_' . $uid;
  $cache = cache_get($cid);
  if (!is_object($cache) || !isset($cache->data[$era])) {
    $campaigns = dosomething_user_my_somethings_campaign_list($uid, $era);
    $somethings = dosomething_user_my_somethings_projects_grants_list($uid, $era);
    $all_somethings = array_merge($campaigns, $somethings);
    if (!is_object($cache)) {
      $cache = new stdClass();
      $cache->data = array();
    }
    $cache->data[$era] = $all_somethings;
    cache_set($cid, $cache->data);
  }
  else {
    $all_somethings = $cache->data[$era];
  }

  $profile_fields = dosomething_user_my_somethings_profile_fields_complete($uid, $era);
  $all_somethings = array_merge($profile_fields, $all_somethings);

  if ($era == 'past') {
    $clubs = dosomething_user_my_somethings_clubs_list($uid);
    $all_somethings = array_merge($all_somethings, $clubs);
  }

  // Get output ready.
  if (count($all_somethings)) {
    $items = array();
    foreach ($all_somethings as $delta => $something) {
      // Set default access for the edit link to FALSE.
      $edit_access = FALSE;
      // Some webform submissions need a conditional path.
      // We don't want it cached, so we add a flag to check the path.
      // We can expand this if there are more pieces have conditional paths.
      if (isset($something->check_path) && $something->check_path && $era == 'current') {
        if (module_exists('dosomething_projects_general') && $something->uri['options']['entity_type'] = 'webform_submission_entity') {
          $submission = $something->uri['options']['entity'];
          $node = node_load($submission->nid);
          $edit_access = webform_submission_access($node, $submission, 'edit');
        }
      }

      if ($era == 'current') {
        if ($something->type == 'campaign') {
          $items[] = l(t('Report back on @title', array('@title' => $something->title)), $something->uri['path']);
        }
        elseif ($something->type == 'project_report') {
          $items[] = l(t('Complete project @title', array('@title' => $something->title)), $something->uri['path']);
        }
        elseif ($something->type == 'grant_application') {
          $items[] = l(t('Complete grant application @title', array('@title' => $something->title)), $something->uri['path']);
        }
        elseif ($something->type == 'profile_field') {
          $items[] = l(t('Add !title', array('!title' => $something->title)), "user/$uid/edit/main");
        }
        $output = array(
          'title' => array(
            '#prefix' => '<h3>',
            '#suffix' => '</h3>',
            'inner' => array(
              '#type' => 'container',
              '#attributes' => array(
                'class' => 'stuff-header',
              ),
              '#children' => t("Stuff You Need To Do"),
            ),
          ),
          'list' => array(
            '#theme' => 'item_list',
            '#items' => $items,
            '#attributes' => array(
              'class' => array(
                'profile-stuff',
              ),
            ),
          ),
        );
      }
      else {
        if ($something->type == 'campaign') {
          $items[] = t('Reported back on @title', array('@title' => $something->title));
        }
        elseif ($something->type == 'project_report') {
          $items[] = t('Completed project @title', array('@title' => $something->title));
        }
        elseif ($something->type == 'grant_application') {
          $items[] = t('Completed application @title', array('@title' => $something->title));
        }
        elseif ($something->type == 'club') {
          $items[] = t('Joined @title', array('@title' => $something->title));
        }
        elseif ($something->type == 'profile_field') {
          $items[] = t('Added !title', array('!title' => $something->title));
        }
        $output = array(
          'title' => array(
            '#prefix' => '<h3>',
            '#suffix' => '</h3>',
            'inner' => array(
              '#type' => 'container',
              '#attributes' => array(
                'class' => 'stuff-header',
              ),
              '#children' => t("Stuff You've Done"),
            ),
          ),
          'list' => array(
            '#theme' => 'item_list',
            '#items' => $items,
            '#attributes' => array(
              'class' => array(
                'profile-stuff',
              ),
            ),
          ),
        );
      }
    }
  }

  return $output;
}

/**
 * Get and format a user's clubs for 'Stuff You've Done'.
 */
function dosomething_user_my_somethings_clubs_list($uid) {
  $somethings = array();
  $clubs = dosomething_user_my_somethings_get_user_group_memberships($uid, 'club');
  if ($clubs) {
    foreach ($clubs as $club) {
      $something = new stdClass();
      $something->title = $club->title;
      $something->type = 'club';
      $somethings[] = $something;
    }
  }
  return $somethings;
}

/**
 * Figure out which user profile fields are complete.
 */
function dosomething_user_my_somethings_profile_fields_complete($uid, $era) {
  $fields = array();
  $account = user_load($uid);
  $profile = profile2_load_by_user($account, 'main');
  $check_fields = array(
    'field_user_birthday',
    'field_user_first_name',
    'field_user_last_name',
    'field_user_hearabout',
    'field_user_official_rules',
    'field_user_why_do_you',
    'field_user_mobile',
    'field_school_reference',
  );

  if (is_object($profile)) {
    foreach ($check_fields as $field_name) {
      if ($era == 'current') {
        if (empty($profile->$field_name)) {
          $field_info = field_info_instance('profile2', $field_name, 'main');
          $label = $field_info['label'];
          $something = new stdClass();
          $something->title = $label;
          $something->type = 'profile_field';
          $fields[] = $something;
        }
      }
      else {
        if (!empty($profile->$field_name)) {
          $field_info = field_info_instance('profile2', $field_name, 'main');
          $label = $field_info['label'];
          $something = new stdClass();
          $something->title = $label;
          $something->type = 'profile_field';
          $fields[] = $something;
        }
      }
    }
  }
  return $fields;
}

