<?php

$plugin = array(
  'title' => t('Petition'),
  'category' => t('Dosomething'),
  'icon' => 'two_three.png',
  'theme' => 'dosomething_panels_petitions',
  'css' => 'petitions.css',
  'regions' => array(
    'top-left' => t('Top - Left'),
    'top-right' => t('Top - Right'),
    'middle' => t('Middle'),
    'bottom-left' => t('Bottom - Left'),
    'bottom-right' => t('Bottom - Right'),
  ),
);
